### ISSUE TITLE
FYI: #[must_use] will "soon" work directly on traits

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#108]
See https://github.com/rust-lang/rust/issues/55506#issuecomment-440381411.

Should be applicable on `Strategy` directly and might be a thing to consider when we raise the rustc version in the next breaking change (I think it'll be 1.32, Fri Jan 18 2019).

**Comment by AltSysrq** [comment]
`Strategy` now is `#[must_use]` as of 0.9.0.
