### ISSUE TITLE
Optional trailing comma matching in the 'proptest' macro

### ISSUE THREAD

**Issue by rjsberry** [AltSysrq/proptest#111]
Functions with trailing commas inside a `proptest` macro will fail to match:

```rust
proptest! {
    #[test]
    fn test_foo(
        a in any::<u8>(),
        b in any::<u8>(),
        c in any::<u8>(),
        d in any::<u8>(),
        e in any::<u8>(),
        f in any::<u8>(), // <--
    ) {
        // ) {
        // ^ no rules expected this token in macro call
    }
}
```

**Comment by AltSysrq** [comment]
I will see if I can address this in the next release, which will hopefully be in the near future .

**Comment by AltSysrq** [comment]
I believe 0.9.0 should allow trailing commas everywhere now. If you find a case I missed, please reopen this issue.
