### ISSUE TITLE
Add a TestRunner that uses fuzzer for random generation.

### ISSUE THREAD

**Issue by Eh2406** [AltSysrq/proptest#117]
If I understand correctly a big part of what a `Strategy` does is convert randomness from a `TestRunner` into a specific type, so that a test can be run on it. And a large part of the work in running `cargo-fuzz` is making a `fuzz_target` that takes `&[u8]` and converts it into something worth testing. So if we had an alternative `TestRunner` that could use `&[u8]` as its source of randomness, then it would be easy write a `fuzz_target` that can use the excellent syntax of proptest to define its assertions. (and possibly get shrinking for free.) To put it differently this would allow code reuse between the growing library/ecosystem of proptest `Strategy`s  and the ecosystem of fuzz testing.

cc https://github.com/blt/bughunt-rust/issues/2
cc https://blog.troutwine.us/2018/10/08/hunting-for-bugs-in-rust/

**Comment by AltSysrq** [comment]
I believe 0.9.1 has what's needed here.

```rust
let entropy: &[u8] = get_some_bytes();
let mut runner = TestRunner::new_with_rng(
    Config::default(),
    TestRng::from_seed(RngAlgorithm::PassThrough, entropy));
```

Please reopen if this addition isn't sufficient.
