### ISSUE TITLE
128-bit support

### ISSUE THREAD

**Issue by Lokathor** [AltSysrq/proptest#119]
```
error[E0277]: the trait bound `std::ops::Range<u128>: proptest::strategy::Strategy` is not satisfied
  --> tests\jump_tests.rs:74:1
   |
74 | / proptest! {
75 | |   #[test]
76 | |   fn prop_for_jump_lcg128(s in 0..core::u128::MAX, j in 0..core::u16::MAX) {
77 | |     // Note(Lokathor): Yes, `j` is supposed to be only up to `u16`, or the test
...  |
89 | |   }
90 | | }
   | |_^ the trait `proptest::strategy::Strategy` is not implemented for `std::ops::Range<u128>
```

**Comment by AltSysrq** [comment]
Are you sure you're on the latest version? This feature has been present since 0.8.0.

**Comment by Lokathor** [comment]
Hmm, docs.rs thinks that the latest version is 0.7 though

**Comment by Lokathor** [comment]
Well, I guess there's some sort of weird situation going on that isn't 128-bit support.

Yeah, crates.io shows the 0.8 line, but docs.rs doesn't.

**Comment by AltSysrq** [comment]
docs.rs hasn't been able to process proptest's documentation for quite some time because it is too large.

**Comment by Lokathor** [comment]
oh no :(

Maybe they could be contacted to have the orange "go to latest" warning added to link to the 0.8 docs?

**Comment by AltSysrq** [comment]
The main problem [apparently is large crate-level doc string](https://github.com/rust-lang/docs.rs/issues/23#issuecomment-414062152), which I'm going to move much of into a separate mdbook with the next release, so it may get resolved that way.

**Comment by Centril** [comment]
@AltSysrq Speaking of which... I've been swamped with language team duties as of late; but I'll try to resume some work on proptest soon-ish... :)

**Comment by Lokathor** [comment]
Well yall can mark this as resolved or edit it into a tracker for the docs.rs thing (which doesn't seem to have an issue that i see)

**Comment by AltSysrq** [comment]
Issues are free, I'll make a separate one just for the docs.rs issue.

**Comment by AltSysrq** [comment]
https://github.com/AltSysrq/proptest/issues/120
