### ISSUE TITLE
Documentation in docs.rs is very out of date

### ISSUE THREAD

**Issue by AltSysrq** [AltSysrq/proptest#120]
Currently, docs.rs only has docs on proptest versions up through 0.7.0. The current version of proptest is 0.8.7. Please see the [current documentation](https://altsysrq.github.io/rustdoc/proptest/0.8.7/proptest/).

This may be fixed in the next release as the very large crate doc string will be moved into a separate location.

Additional info: https://github.com/rust-lang/docs.rs/issues/23#issuecomment-414062152

**Comment by QuietMisdreavus** [comment]
Someone brought this to my attention on the Rust Discord today, and i was able to successfully rebuild the documentation for 0.8.7, thanks to https://github.com/rust-lang/docs.rs/pull/227 fixing the issue that prevented it earlier: https://docs.rs/proptest/0.8.7/proptest/

I'm currently back-filling in the versions that failed to build, as well.

**Comment by QuietMisdreavus** [comment]
All the versions between 0.7.0 and 0.8.7 are now hosted on docs.rs.

**Comment by AltSysrq** [comment]
Thanks @QuietMisdreavus !
