### ISSUE TITLE
TestRunner::with_seed()

### ISSUE THREAD

**Issue by Eh2406** [AltSysrq/proptest#125]
In cargo we are using [TestRunner::default()](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/support/resolver.rs#L503) to ensure that our strategies are working well. Unfortunately with the number of places that cargos tests are run we are seeing [spurious failures some](https://github.com/rust-lang/cargo/issues/6613) of the time. I'd like to change that to have a deterministic seed, but I don't see how to do that. I think a deterministic constructor would be part of #121 as well. An alternate way to test strategies is also appreciated.

**Comment by AltSysrq** [comment]
I definitely agree this will be useful. Proptest actually has a similar issue with its own tests failing spuriously for the same reason.

This isn't going to get into 0.9.0 but I will look into it for the next version (which won't take as long as this one since we won't be adding another proc macro crate).

**Comment by AltSysrq** [comment]
0.9.1 brings along several things to this end.

At the lowest level is exactly this, with [`TestRunner::new_with_rng`](https://altsysrq.github.io/rustdoc/proptest/0.9.1/proptest/test_runner/struct.TestRunner.html#method.new_with_rng) and [`TestRng::from_seed`](https://altsysrq.github.io/rustdoc/proptest/0.9.1/proptest/test_runner/struct.TestRng.html#method.from_seed).

For this specific use-case, there's also [`TestRunner::deterministic`](https://altsysrq.github.io/rustdoc/proptest/0.9.1/proptest/test_runner/struct.TestRunner.html#method.deterministic), which is a drop-in replacement for `TestRunner::default` that always uses the same seed.

**Comment by shepmaster** [comment]
> I'd like to change that to have a deterministic seed

@Eh2406 FWIW, I recommend using something like the PR number as the seed for randomized tests in CI. This means that retrying a build will **not** solve flaky failures but instead force contributors to fix the problem. Each new PR will have the chance for a new ordering, however, exercising more paths.
