### ISSUE TITLE
`sample()` and `select()` functions are missing

### ISSUE THREAD

**Issue by vitiral** [AltSysrq/proptest#13]
My use case is a graph, where *all* nodes are randomly created, and then I want to select a subset for each node to connect to when I create the actual graph.

However, there doesn't seem to be either a `sample()` or `select()` api with which to do this.

**Comment by Centril** [comment]
What would be the preferred signatures of `sample()` and `select()`?

So for simplicity let's assume that a `Vec` stands in for a true set.
Then perhaps a `Strategy` which generates a sub-Vec of the `Vec` could be useful?
A simple way to do this is: go through all elements of the list, flip a coin, if yes, add the element to the set, else leave it out. We can accomplish this by generating a `Vec<bool>` (of equal length to the nodeset Vec) which is then zipped with the nodeset Vec and then filter based on the value of the bool.
This may be sub-optimal, but it should work.

**Comment by vitiral** [comment]
I think I would prefer #14 over this, since #14 is more general use case and can be used in any way that the user needs, including using any container they wish.

I think it would be a mistake to *not* use `Rng` under the hood for this. `sample` takes a *specific number* of samples, so probabilistically "flipping a coin" is not enough to guarantee how many you will get. Trying to select N values from M where every value in M has an *equal chance of being selected* is actually fairly non-trivial if I recall correctly.

A really simple case would be to shuffle the data and select the first N, but this will take `O(M)` time for N values (where `N < M`), so is certainly not ideal.

**Comment by vitiral** [comment]
I'm looking at this more and questioning whether #14 is actually the way to go... once we open up that can of worms it may be difficult to walk it back.

Intead, I think the right way to go about it is for the container-strategies (i.e. HashMapStrategy, etc) to all implement a `ContainerStrategy` trait, this would have a method `prop_sample(num: usize)` and `prop_select()` on it.

**Comment by Centril** [comment]
Could you clarify what `sample` and `select` do exactly, possibly including signatures of these methods?
My comment was specific to your particular use case and not `sample` or `select` in general since I'm not sure what these entail.

**Comment by vitiral** [comment]
@Centril lol literally just doing that :)

**Comment by Centril** [comment]
I don't think that description is sufficient, at least not for me to implement this independently - I'm still not sure what these operations actually do...

From what I understand, `VecStrategy::prop_sample(num: usize)` simply generates a vec where `.len() == num`. This is simply: `proptest::collection::vec(strategy_for_elem, num .. num)`.

So what is `.select()`? does it select a subset of elements from a generated `Vec` ? A longer description would be instructive here.

**Comment by vitiral** [comment]
what is `strategy_for_elem` in your case? Is that a filter?

`select()` just selects a single element, `sample(num: USizeStrategy)` selects a random number of them (but like you said, it selects *exactly* that number, so if you had a physical num (not a strategy) then it could be represented as `num .. num`).

**Comment by vitiral** [comment]
the code is [actually pretty basic](https://doc.rust-lang.org/rand/src/rand/lib.rs.html#1031-1047), I might be able to actually implement this as a workaround.

**Comment by Centril** [comment]
Here `strategy_for_elem` is a strategy for generating one element of type requested type, so for example: `proptest::collection::vec(proptest::num::u8::ANY,  100..100)` is a strategy that generates a vector of exactly `100` elements of any `u8`.

If you want to randomize the number of elements too you can use `prop_flat_map`:

```rust
use proptest::num::{u16, u8};
use proptest::collection::vec;

// A strategy that generates (0 ..= std::u16::MAX) elements of u8:s.
let strategy = u16::ANY.prop_flat_map(|len| vec(u8::ANY,  len..len));
```

**Comment by Centril** [comment]
A smarter way to put this is (approximately):

```rust
use proptest::num::u8;
use proptest::collection::vec;
let strategy = vec(u8::ANY,  0 .. std::u16::MAX);
```

**Comment by vitiral** [comment]
but that selects from all `u8`'s, it doesn't select from a precreated list.

What I would like to do is something like:

```
use proptest::num::u8;
use proptest::collection::vec;

/// get a vector and a random sample of elements from that vector
let strategy = vec(u8::ANY,  1 .. std::u16::MAX)
    .prop_map(|v| (v, v.prop_sample(1 .. v.len()));
```

**Comment by Centril** [comment]
Now I know what you want =)

Doing this as a trait is probably reasonable.

Is the following valid?
```
([1, 2, 3, 4], [2, 1]) <-- note that the ordering has changed.
```

What are the semantics of (un)shrinking?
A proposal:
+ The `ValueTree` should be generated with an initial sub-`Vec`.
+ For `simplify()` the `ValueTree` should remove one tail element from the last-returned sub-`Vec` if it hasn't reached the minimum length. This removed element is added to another `Vec` stored in the `ValueTree`
+ For `complicate()`, the last removed element should be re-added.

The type is thus:

```rust
struct SubVecValueTree<T: Clone> {
    minimum: usize,
    current: Vec<T>,
    removed: Vec<T>,
}
```

A version on this is to alternate between removing the first / last element. It depends on if you want to bias towards the first element being the simplest, or if you want the middle element to be the simplest (in which case you alternate).

I think `.select` is unnecessary since we already have `Union`, so you can do:
```rust
Union::new_weighted(my_vec.into_iter().map(|elt| (1, Just(elt))))
```
Tho for performance a more specialized solution may be right.

**Comment by vitiral** [comment]
> Is the following valid?

yes, they can be out of order.

> What are the semantics of (un)shrinking?

Since the returned vec is random anyway, I would do it this way:
- `simplify()` removes a *random* element from `current` and adds it to the `removed`
- `complicate()` takes a *random* element from `removed` and adds it to `current`.

Agree that `sample` is more important than `select`. Heck, you could even `sample` one element as a vector and then take it's 0th index.

**Comment by vitiral** [comment]
Also, sorry I wasn't more clear. I'm still trying to wrap my head fully around this library. It is SO awesome though!

**Comment by Centril** [comment]
That's OK =)

The operations of `ValueTree` should be deterministic. Randomness comes from the generation of the `ValueTree` itself. The only way to be random inside the `ValueTree` is to clone the `XorShiftRng` which means that any mutation made to it inside the `ValueTree` is not persisted across `new_value` runs.
This bit is instructive: https://docs.rs/proptest/0.3.1/src/proptest/collection.rs.html#344-350

I guess you could modify `TestRunner` by adding a function `ValueTree::yield_rng(self) -> Option<XorShiftRng> { None }` whereby the `ValueTree`  may clone the `TestRunner`'s `XorShiftRng` during construction and give back the modified version which the `TestRunner` may set to itself before the next `new_value` call. However, this mechanism does not compose well.

Given that the elements can be out of order, this is not a sub-list operation, but rather: `sublist(shufle(vec), min..max)` - this is natural for sets, since there is no real ordering - however, for Vec, I think this is a bit weird to allow the elements to be out of order. It might be useful to provide a shuffle operation for `Vec` which does not shrink - as a different operation. Then you can compose the operations.

**Comment by vitiral** [comment]
I'm a bit confused -- are not ALL operations, even "random" ones deterministic if you use a seed?

If a non-random ordering is what you want that should be easy to implement -- just preserve the index and then sort by it -- but this will have quite a large impact on performance for large selections.

Since the shuffle isn't *suitably random* anyway, I agree that `shuffle` should be a separate operation anyway. I'm not sure if preserving order should be a major design choice or not. If that were desired I would call it `sample_stable` since it reminds me of stable-sorting.

**Comment by vitiral** [comment]
Ok, I think I see -- you would have to clone the `Rng` in the `VecStrategy` in order to later use it... ya that isn't ideal, but I don't think it's TOO bad.

Your strategy isn't bad either -- I would say it's probably fine. You could even deterministically move the index from right to left or something, moving values back and forth as you go and keeping elements that caused the test to fail. Obviously this is slow, but it's fine to be slow while your shrinking right?

**Comment by vitiral** [comment]
Also, I would make `removed` a queue. Imagine the following case:

```
[1,2,3,4,5] # fail
   # removed = [5]
[1,2,3,4]  # fail
    # removed = [5, 4]
[1,2,3]  # pass, add pop from take from queue
[1,2,3,5] # pass, move one index back
   # removed = [4]
[1,2,5] # pass, move one index back
   # removed = [4,3]
[1,5] # pass, move one index back
    # removed = [4,3,2]
[5]  # pass, swap with queue
[4] # fail, minimum case
    # removed = [3,2,5]
```

**Comment by AltSysrq** [comment]
Backing away from the theory here for a moment to give my opinions on the original request:

> `select()`

As @Centril mentioned above, this is already possible with the current API, it's just a bit of a mouthful. It'd be fairly easy to add a convenience for this and definitely worth it.

> `sample()`

Also useful and not easily implemented from the user perspective.

As far as implementation goes, most of it could be done by reusing the logic we already have for `BitSet`.

- Add a new strategy for `BitSetLike` types which does an n-choose-k algorithm to choose the initial bits. The current `BitSetValueTree` shrinks to all bits being zero; local filtering is sufficient to keep the set size to a minimum.

- Selecting elements is done by `prop_map()`ing over the bitset strategy and choosing elements whose bit is set.

- Add a convenience to put these pieces together.

Besides being less code, it also doesn't require constantly moving larger pieces of data around.

**Comment by Centril** [comment]
I guess the better idea is to just store the entire sub-vector and then store a slice to the vector as well in the style of [owning_ref](https://docs.rs/owning_ref/0.3.3/owning_ref/). Then you can modify the slice without any allocation in `simplify()` or `complicate()`.

**Comment by vitiral** [comment]
wait, I think I've confused myself... is this code even valid?

```
let strategy = vec(u8::ANY,  1 .. std::u16::MAX)
    .prop_map(|v| (v, v.prop_sample(1 .. v.len()));
```

`v` is a *real vector* is it not? Can you call `prop_sample` on a `Vec`?

**Comment by vitiral** [comment]
hmm... based on my above realizations I'd say `sample` needs to be a function, not a method. So it would be used in this way:

```
let vec_strategy = vec(u8::ANY,  1 .. std::u16::MAX)
    .prop_map(|v| (Just(v), prop::sample(v, 1 .. v.len()));
```

We have to be able to create a *strategy* out of a *real vector*, so it works kind of like `Just`. Am I making any sense?

**Comment by Centril** [comment]
@AltSysrq  How do you feel about:

1. How do you feel about `shuffle` (with no shrinking)
2. having a trait for "sample" (I'm going to call it `part_of` henceforth)?
I think it might be nice to have since some things may be optimized for non-Vec, and they may also have different semantics wrt. ordering...
3. speaking of... should `Vec::part_of` preserve ordering of input `Vec` in the output `Vec`?
4. it might be nice to have a `part_of_shuffle` which acts like `part_of` but shuffles first.

So how about:

```rust
pub trait ContainerStrategy /* <-- bikeshed name */ {
    fn prop_part_of(self /* perhaps &self ? */)
        // in reality concrete types for now since impl trait is not stable.
        // use some associated type instead.
        -> impl Strategy<Value = impl ValueTree<Value = Self>>;
}

// Trait is separate because some types have no ordering, notably `HashSet`.
pub trait ShuffleStrategy /* <-- bikeshed */ {  
    fn prop_shuffle(self)
        -> impl Strategy<Value = impl ValueTree<Value = Self>>;
}
```

@vitiral You have to `prop_flat_map` instead if you are returning a `Strategy`, so:

```rust
vec(u8::ANY,  1 .. std::u16::MAX)
    .prop_flat_map(|v| (Just(v), v.prop_part_of(1 .. v.len())));
```

**Comment by AltSysrq** [comment]
The constructor would probably be something like `VecStrategy::sample_from(collection, size)` with a companion `proptest::vec::sample_from` free function. `prop_flat_map` would come in if the vector itself were produced by a strategy, so something like

```rust
let strategy = vec(u8::ANY, 1 .. std::u16::MAX)
    .prop_flat_map(|v| {
        // Appease the borrow checker
        let len = v.len();
        vec::sample_from(v, len)
    });
```

**Comment by vitiral** [comment]
@AltSysrq that makes sense and is in-line with what I was saying. Do you think `len` should be either an integer-strategy OR a hard integer (I'm not sure if that is already the case, does `usize` implement IntStrategy?).

I can see a use case for wanting to sample a random number of elements (but within a certain range)... mainly that is my use case :)

Also, I assume `v` just needs to be a type implementing `IntoIter` right? It doesn't have to be a vector.

**Comment by AltSysrq** [comment]
@Centril

1. Positively, it's just a matter of generating a RNG for the value so the shuffling is consistent. It might make sense to shrink to a non-shuffle.

2. I'm not sure what that trait would look like, especially since there's no existing trait for collections.

3. I think it should. The `BitSet` implementation I suggested does this and it makes the behaviour more deterministic. It also makes it a proper [subsequence](https://en.wikipedia.org/wiki/Subsequence) operation.

4. If we implement both building blocks, it's not much cost to add this too.

I don't care for the name `part_of`; it sounds more like slicing. It would be better to stick to an established name, either from a major library (thus `sample`) or a mathematical operation (e.g., `subsequence` or `choose_k`).

**Comment by vitiral** [comment]
I guess that is easily composable

```
let vec_strategy = vec(u8::ANY,  1 .. std::u16::MAX)
    .prop_flat_map(|v| (1 .. v.len(), Just(v))
    .prop_flat_map(|(num, v)| (Just(v), prop::sample(v, num));
```

**Comment by AltSysrq** [comment]
@vitiral 

> Do you think len should be either an integer-strategy OR a hard integer (I'm not sure if that is already the case, does usize implement IntStrategy?).

The current strategies for creating collections require the size to be a range, and this new API would be the same. Ideally we'd accept any range or a fixed integer, but I don't think all the functionality to support that is stable in std yet. Note that it's not actually an arbitrary strategy; because it knows the size range directly, it can avoid all the disadvantages that would come from using `prop_flat_map`.

> Also, I assume v just needs to be a type implementing IntoIter right? It doesn't have to be a vector.

It would likely be possible to use just `IntoIter`, but in practise it'll need to run over that list many times to just select a (possibly tiny) subset, so it's probably best for both efficiency and simplicity to just buffer into a vector (though the API could certainly take an `IntoIter` anyway.)

**Comment by Centril** [comment]
@AltSysrq 

1. How would shrinking to a non-shuffle work?
2. 

```rust
pub trait ContainerStrategy {
    type Output;
    fn prop_part_of(self, bounds: Range<usize>) -> Self::Output;
}
```

then we can have:

```rust
// More deref types when specialization lands, for example:  AsRef<[T]>.

impl<T: Clone> ContainerStrategy for Vec<T> {
    type Output = Vec<T>;
    fn prop_part_of(self) -> Self::Output { ... }
}

impl<T: Clone> ContainerStrategy for HashSet<T> {
    type Output = HashSet<T>;
    fn prop_part_of(self) -> Self::Output { ... }
}
```
3 + 4. great =)
5. Where's the name `sample` from?  `subsequence` sounds right for `Vec´, but not for `HashSet`. `choose_k` is probably too hard to find...?

**Comment by AltSysrq** [comment]
@Centril 

1\. `simplify()` => `current_value()` just passes the original collection through unchanged; `complicate()` => `current_value()` goes back to doing the original shuffle.

2\. I see, that looks good. Would probably make sense to put an equivalent of the current free functions there as well.

5\. `rand::sample`(https://docs.rs/rand/0.3.18/rand/fn.sample.html). I get your point about `subsequence`; conversely, there's also "subset" or "combination" that works for `HashSet`/`HashMap` but not `Vec`. I think I'd definitely lean to `sample` at this point.

**Comment by vitiral** [comment]
@AltSysrq 
> It would likely be possible to use just IntoIter, but in practise it'll need to run over that list many times to just select a (possibly tiny) subset

The [implementation in `rand`](https://doc.rust-lang.org/rand/src/rand/lib.rs.html#1031-1047) has to run throught the list exactly once, so hopefully that performance would be possible here.

@AltSysrq I'm confused by the variable name `bounds`, are you selecting it defines a range of valid values? I'm not opposed to this, I actually think it would be perfect for my use case. I assume the "bounds" would be randomized as well then?

Also nitpick, you forgot to add them in your `impl`s

**Comment by Centril** [comment]
@AltSysrq 

1. Oh ;) I was envisaging different degrees of chaos you could simplify to ^.^ If not, then `simplify() / complicate()` are essentially just a `mem::swap`.  Should the `ValueTree` have its own independent `XorShiftRng`?

2. Agreed, free functions make sense.

5. Original Haskell QC calls the most similar operation [`subListOf`](http://hackage.haskell.org/package/QuickCheck-2.10.1/docs/Test-QuickCheck-Gen.html#v:sample-39-) , but that has the same problems as `subsequence`. I guess `prop_sample` is the least bad - The name `part_of` was conceived in trying to find the common denominator of `subsequence` and `subset`.

@vitiral I think you meant to highlight me at the end there?
In `prop_sample(self, bounds: Range<usize>) -> Self::Output` the argument `bounds` refers to the minimum amount of elements, and and the maximum amount of elements in `Self::Output`. If `self.len() < bounds.high` then `self.len()` is used. If `self.len() < bounds.low` you get a panic (or perhaps not? discuss...).

**Comment by AltSysrq** [comment]
> The implementation in rand has to run throught the list exactly once, so hopefully that performance would be possible here.

Yes. I was thinking about the case of a single, constant array where every test input would be derived from the same available selection, which feels like it might be a more common use-case.

>  the variable name `bounds`

Sorry, I meant that that's the bounds on the size of the output.

**Comment by AltSysrq** [comment]
> Should the ValueTree have its own independent `XorShiftRng`?

I don't think you have much of a choice since you won't have access to the one on `TestRunner` at that point. Presumably you'll want to start from the same seed (for a particular `ValueTree`) each time too.

**Comment by Centril** [comment]
@AltSysrq I was thinking that `SuffleStrategy::new_value(...)` shuffles the input and then yields:

```rust
pub struct ShuffleValueTree<T> {
    current: T,
    other: T,
    is_simple: bool,
}

impl<T: Clone> ValueTree for ShuffleValueTree<T> {
    type Value = T;
    fn current(&self) -> Self::Value { self.current.clone() }
    fn simplify(&mut self) -> bool {
        if !self.is_shuffled { return false; }
        mem::swap(&mut self.current, &mut self.other);
        self.is_shuffled = false;
        true
    }

    fn complicate(&mut self) -> bool {
        if self.is_shuffled { return false; }
        mem::swap(&mut self.current, &mut self.other);
        self.is_shuffled = true;
        true
    }
}
```

But perhaps this was not the idea at all?

**Comment by AltSysrq** [comment]
Oh, that works too and is a lot simpler. :+1:

**Comment by Centril** [comment]
@AltSysrq Tho there might be degrees of shuffled:ness? (which this doesn't capture)

**Comment by AltSysrq** [comment]
I had been thinking of something like

```rust
// Generics simplified for conciseness
struct ShuffleValueTree<V : ValueTree> {
    inner: V,
    rng: XorShiftRng,
    shuffle: bool,
}

impl<V : ValueTree> ValueTree for ShuffleValueTree<V> {
    type Value = V::Value;
    
    fn current(&self) -> V::Value {
        let mut collection = self.inner.current();
        if shuffle {
            // We start from the same RNG every time, so every call shuffles the same way
            self.rng.clone().shuffle(&mut collection);
        }
        collection
    }

    fn simplify(&mut self) -> bool {
        // TODO: If already simplified, call `inner.simplify()`
        let r = self.shuffle;
        self.shuffle = false;
        r
    }

    fn complicate(&mut self) -> bool {
        let r = self.shuffle;
        self.shuffle = true;
        !r
    }
}
```

so no "degrees of shuffledness".

Actually, now that I wrote that, I'm not sure the swap approach works, since `current()` yields an owned value, and it doesn't have an obvious way to continue simplifying the source `ValueTree` without having separate logic to then re-shuffle it.

**Comment by Centril** [comment]
@AltSysrq Well, there's a `.clone()` there, so it should work - but it `T` was a `ValueTree::Value`, not a `ValueTree` - but that's quite boring I guess. Your solution is more general 👍.

I'll investigate if "degrees of shuffledness" is a doable thing.

**Comment by Centril** [comment]
@AltSysrq For a "degrees of shuffledness" we could simply modify the [Fisher-Yates](https://docs.rs/rand/0.3.16/src/rand/lib.rs.html#586-594) algorithm like so:

```rust
extern crate rand;

use rand::{thread_rng, Rng};

fn shuffle<T, R: Rng>(rng: &mut R, values: &mut [T], degree: usize)
{
    if degree == 0 { return; }
    let len = values.len();
    // magic computation, come up with something better...
    let prob_to_swap = ((len - degree) as f64).sqrt().ceil() as usize;

    let mut i = len;
    while i >= 2 {
        // invariant: elements with index >= i have been locked in place.
        i -= 1;
        // 1 / prob_to_swap chance to swap.
        if rng.gen_range(0, prob_to_swap) == 0 {
            // lock element i in place.
            values.swap(i, rng.gen_range(0, i + 1));
        }
    }
}

fn main() {
    let mut rng = thread_rng();

    for degree in 0..20 {
        let mut vec = (0..20).collect::<Vec<u8>>();
        shuffle(&mut rng, &mut vec, degree);
        println!("{:?}", vec);
    }
}
```

**Comment by AltSysrq** [comment]
@Centril That might be a bit too chaotic since it perturbs the RNG as it shrinks (both due to not calling `gen_range()` the same number of times before each element, and I assume `gen_range()` uses rejection sampling so changing the range would perturb it that way too).

Maybe something like this? (Not 100% confident of the shrinking logic)

```rust
// Generics simplified for conciseness
struct ShuffleValueTree<V : ValueTree> {
    inner: V,
    rng: XorShiftRng,
    // max_shuffle is the maximum distance any element will be perturbed in a
    // single step; as it is reduced to zero, the shuffle makes fewer and fewer
    // changes to the output.
    // Initialised to the size of the output.
    max_shuffle: usize,
    // The maximum value that `complicate()` can increase `max_shuffle` to.
    max_max_shuffle: usize,
    // The minimum value that `simplify()` can decrease `min_shuffle` to.
    // Starts at 0.
    min_max_shuffle: usize,
}

impl<V : ValueTree> ValueTree for ShuffleValueTree<V> {
    type Value = V::Value;

    fn current(&self) -> V::Value {
        let mut collection = self.inner.current();
        let mut rng = self.rng.clone();
        for i in 0..collection.size() - 1 {
            // By generating the index outside any conditional, we produce the
            // same sequence of candidate swaps regardless of `max_shuffle`.
            let other = rng.gen_range(i + 1, collection.size());
            if other - i < self.max_shuffle {
                collection.swap(i, other);
            }
        }
        collection
    }

    fn simplify(&mut self) -> bool {
        self.max_max_shuffle = self.max_shuffle;
        if self.max_shuffle > self.min_max_shuffle {
            self.max_shuffle -= 1;
            true
        } else {
            self.inner.simplify()
        }
    }

    fn complicate(&mut self) -> bool {
        if self.max_shuffle < self.max_max_shuffle {
            self.max_shuffle += 1;
            self.min_max_shuffle = self.max_shuffle;
            true
        } else {
            self.inner.complicate()
        }
    }
}
```

**Comment by Centril** [comment]
@AltSysrq That shrinking logic seems like a better idea with a better notion of chaos (locality / delta).

@vitiral `bounds` refers to (min/max) - an `amount` is not a `Range<usize>` - but what a parameter is named isn't that important. What is important is giving a clear documentation about the behaviors of the method. I think fail-fast behavior in response to what is clearly a programmer-error is appropriate - the standard library does use panics for that in certain places - it is even more appropriate for a testing lib.

To be clear, `subsequence` effectively would first randomize `amount in [bounds.start, bounds.end]` and then use `sample` with that.

**Comment by Centril** [comment]
Done initial work on `subsequence` - todo: tests and more `CollectionStrategy` impls. Work in #8 .

**Comment by Centril** [comment]
@AltSysrq So, looking at it again... is there a reason it isn't just:

```rust
    fn simplify(&mut self) -> bool {
        if self.max_shuffle > self.min_max_shuffle {
            self.max_shuffle -= 1;
            true
        } else {
            self.inner.simplify()
        }
    }

    fn complicate(&mut self) -> bool {
        if self.max_shuffle < self.max_max_shuffle {
            self.max_shuffle += 1;
            true
        } else {
            self.inner.complicate()
        }
    }
```
would this cause an infinite loop perhaps? so you are trying to ensure that it's only possible to complicate once once fully simplified?

The logic of `.current()` looks good.

**Comment by AltSysrq** [comment]
@Centril 

> is there a reason it isn't just:

It needs to ensure that calls to `complicate()` after a `simplify()` don't increase the complexity beyond where it was immediately before the call to `simplify()`.

**Comment by Centril** [comment]
@AltSysrq Right - then it looks good =) I guess you can add the shuffle feature?

**Comment by vitiral** [comment]
@Centril is the shuffle feature necessary for this PR?

**Comment by AltSysrq** [comment]
I have shuffle added to the `0.3.2-changes` branch. In the process I discovered a bug in `VecStrategy`; I'm going to be adding some tests for that specific problem to all the non-trivial strategies, but that's the only thing left blocking the release of 0.3.2 at this point.

**Comment by Centril** [comment]
What is necessary or not is ofc entirely up to @AltSysrq =)

**Comment by AltSysrq** [comment]
`sample::select()` and `sample::subsequence()` are added in 0.3.2, as well as the discussed `prop_shuffle` combinator.
