### ISSUE TITLE
Recursive strategies?

### ISSUE THREAD

**Issue by araspik** [AltSysrq/proptest#133]
I'm writing a strategy that produces `Tag`s. The thing is, each `Tag` may contain other sub-`Tag`s. So I wrote up a strategy that, 75% of the time, does not have subtags, and 25% of the time, has `1..32` subtags:
```rust
let num = prop_oneof![1 => (1usize..32), 3 => (0usize..1)];
```
The thing is, in order to use `collection::vec(tag_strategy(), num)`, the function will recurse forever. Instead, I'm trying to write this:
```rust
let num = prop_oneof![1 => (1usize..32), 3 => (0usize..1)];
let tags = prop::collection::vec(if num > 0 {
    tag_strategy()
} else {
     Just(Tag::new("")) // Blank element, will never be generated anyways
}, num);
```
The issue is that `Just` and `tag_strategy` are of different types completely. `tag_strategy()` has type `Map<Flatten<Map<..., [closure]>>, [closure]>`, and `Just` is, well, `Just<Tag>`. How do I get this to work?

**Comment by AltSysrq** [comment]
The thing you are looking for is [`prop_recursive`](https://altsysrq.github.io/rustdoc/proptest/0.9.1/proptest/strategy/trait.Strategy.html#method.prop_recursive). I don't know enough about your `Tag` type to give a concrete example, but hopefully the doc example will be useful.

**Comment by araspik** [comment]
Sorry! It's not on [the `github.io` docs for `proptest`](https://altsysrq.github.io/rustdoc/proptest/latest/proptest/index.html), so I was a bit confused.

**Comment by AltSysrq** [comment]
No worries, happy to help!

**Comment by araspik** [comment]
I'm writing basically the same thing as the given example (a parsing library), so it turned out to be extremely useful. Thanks!
