### ISSUE TITLE
Minor bug in the book

### ISSUE THREAD

**Issue by dunmatt** [AltSysrq/proptest#138]
In [1.2.10](https://altsysrq.github.io/proptest-book/proptest/tutorial/recursive.html) it says:

> This also uses the prop_oneof!, which we haven’t seen yet but should be self-explanatory.

despite the fact that `prop_oneof!` is introduced and described well in [1.2.8](https://altsysrq.github.io/proptest-book/proptest/tutorial/enums.html).  I think it'd be safe to simply delete the whole sentence.

**Comment by AltSysrq** [comment]
You are correct. This has been fixed.
