### ISSUE TITLE
Shrinking time can last forever by default

### ISSUE THREAD

**Issue by Valloric** [AltSysrq/proptest#145]
Having made a change to my codebase, I ran my tests. I found a proptest was getting stuck in what appeared to be an infinite loop.

After much debugging with GDB, I figured out it was proptest's shrinking process that was taking forever.

After yet more digging, I found the PROPTEST_MAX_SHRINK_TIME env var and that the [default for `max_shrink_time` was 0](https://docs.rs/proptest/0.9.3/proptest/prelude/struct.ProptestConfig.html#structfield.max_shrink_time), meaning shrink with no timeout (AKA looping forever is possible).

**I don't think this a good default value**. It wasn't at all obvious what was going on, and I can imagine every single user would rather see a proptest fail with a big input than see their tests stuck in an infinite loop.

It would make sense to have a reasonable default for the shrink timeout (say, 5 seconds) and then print out a message at the bottom of the output saying something like "shrinking timeout hit, use PROPTEST_MAX_SHRINK_TIME with a high value to possibly get a smaller test case". This would strike me as a much more ideal UX.

Thanks again for proptest, it's awesome!

**Comment by AltSysrq** [comment]
I think I agree with you. I will plan on changing the default in the next release. IMHO 5 seconds is a bit too aggressive; I'll probably do something around 30 or 60.

**Comment by Valloric** [comment]
Frankly, I think 5 seconds isn't aggressive enough. :) It should probably be 2 seconds.

The situation doesn't improve much if the default is 30 seconds; my test suite executes in ~2 seconds normally, so I if I see a test getting stuck, I'm going to assume I've written an infinite loop. Nobody will sit in front of `cargo test` waiting 30 seconds for a test that normally finishes immediately. Certainly not for 60 seconds. Nobody will think "oh, it's proptest shrinking input, let me wait a bit."

Even now that I know shrinking can take quite a bit of time, I wouldn't want to wait even 10 seconds for a shrunk input because I usually don't need to know the input that caused the breakage, only the assert backtrace to know what to fix. 

This is why having that message in the output saying "here's an env var to tweak to shrink further" is rather important. It helps people **in that rare use-case** of "I don't know why this is failing and I need the best test case you can give me to help me figure it out". This is _not_ the default workflow.

**Comment by AltSysrq** [comment]
I realised there's a way for both of us to get what we want here — base the default limit for the number of shrinking iterations on the number of test cases, namely 4x that number. So if your test normally takes 1s, the worst failing case is 5s (assuming the code doesn't fail by getting slow itself, of course); and my tests which always take a while to run are also given a long time to shrink.

The above is now in 0.9.4.

**Comment by Valloric** [comment]
That's a great idea! Thanks for implementing it. :)
