### ISSUE TITLE
provide basic examples for implementing Arbitrary

### ISSUE THREAD

**Issue by marcmo** [AltSysrq/proptest#150]
it would be very helpful for newcomers to see some examples of how to implement `Arbitrary` for structs, enums, ...
```
pub enum Kind {
    Request(u8),
    Response(u8),
}
pub struct MyType {
    pub a: bool,
    pub b: String,
    pub kind: Kind,
}
impl Arbitrary for MyType {
... // for all a
... // for all b where b.trim().len() >= 3
... // for all kinds with Request(x) where 0 <= x <= 10, Response(y) where 0 <= y <= 10
}
```
would go a long way towards making the library more useable.
thanks!

**Comment by marcmo** [comment]
I guess [proptest/proptest/src/arbitrary/sample.rs](https://github.com/AltSysrq/proptest/blob/master/proptest/src/arbitrary/sample.rs) together [with proptest/proptest/src/sample.rs](https://github.com/AltSysrq/proptest/blob/master/proptest/src/sample.rs)  is kind of an example but honestly, this is way over the top of my rust head.

**Comment by AltSysrq** [comment]
I will plan on adding an example in the next release.

But basically, I'd recommend first writing a function that returns a strategy (which the docs have plenty of examples of) and once you have that working, wrapping it in the `Arbitrary` implementation.

```rust
fn my_type_strategy() -> StrategyTypeHere {
  // implementation...
}

impl Arbitrary for MyType {
  // If your strategy function takes parameters, use a tuple or something to be able
  // to pass them along
  type Parameters = ();

  type Strategy = StrategyTypeHere;

  fn arbitrary_with(args: ()) -> Self::Strategy {
    my_type_strategy()
  }
}
```

`StrategyTypeHere` needs to be an actual concrete type which can get quite hairy so you may find it more trouble than it's worth. (If you were just using the strategy function directly, you could use `-> impl Strategy<Value = MyType>`.)

What you describe in your example could also be implemented via the `proptest-derive` crate. Something like:

```rust
use proptest_derive::Arbitrary;

// If this is outside of test code, you probably need all the attributes
// to be wrapped in `#[cfg_attr("test", ...)]`
#[derive(Arbitrary)]
pub enum Kind {
  Request(#[proptest(strategy = "0u8..=10")] u8),
  Response(#[proptest(strategy = "0u8..=10")] u8),
}

fn long_enough_when_trimmed(s: &String) -> bool {
  s.trim().len() >= 3
}

#[derive(Arbitrary)]
pub struct MyType {
  pub a: bool,
  #[proptest(regex = ".{3,}", filter = long_enough_when_trimmed)]
  pub b: String,
  pub kind: Kind,
}
```

**Comment by marcmo** [comment]
wow...I had no Idea you could do that with `proptest-derive`!!
thanks so much for sharing this, it already will help quite a bit.
yeah the `Strategy`-type seems daunting...will try my luck with `derive` first.

**Comment by marcmo** [comment]
still have trouble applying this to my usecase. 2 facts seem to complicate matters:
1.I derive from `Arbitrary` only in my test configuration
2.one field is not a `String` but an `Option<String>`...can I still use these regex restrictions @AltSysrq ?
```
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct MyType { 
    pub my_id: Option<String>,
}
```
