### ISSUE TITLE
Help implementing Arbitrary on an array of ArrayVec

### ISSUE THREAD

**Issue by rw** [AltSysrq/proptest#171]
This is a helpful library, and in many cases, I've found it to be more ergonomic than the quickcheck library.

One issue I'm struggling with, though, is implementing Arbitrary for an array of [ArrayVec](https://github.com/bluss/arrayvec) values. I think the ideal code would look like:

```rust
struct MyArrayVec(ArrayVec<[u8; 16]>); // Newtype-style wrapper

impl Arbitrary for MyArrayVec {
    // what goes here?
}

#[derive(Arbitrary)]
struct MyStruct {
  items: [MyArrayVec; 10],
}
```

But, I don't know the idiomatic way to do it. I see that the `arbitrary!` macro is not public in this crate (not that I would know how to use it). Perhaps the answer to this question could be added to a FAQ or HOWTO document. Thanks!

**Comment by Centril** [comment]
> I see that the `arbitrary!` macro is not public in this crate (not that I would know how to use it).

Yeah, it's fairly opaque, but it's just for internal use to reduce repetition for all the Arbitrary standard library impls proptest provides.

**Comment by Centril** [comment]
> But, I don't know the idiomatic way to do it.

This is going to be a bit tricky because `ArrayVec` would need to provide the `Arbitrary` impl or otherwise you'll get into orphan rule problems. cc @bluss (tho I doubt `arrayvec` would want to take on an optional proptest dependency).

I do think `MyArrayVec` is the approach you'll need to go with. I would look for inspiration from the `impl<T: Arbitrary> Arbitrary for [T; N]` and `impl<T: Arbitrary> Arbitrary for Vec<T>` implementations. In particular the last one should provide what you need but for the general case rather than for a fixed upper bound.

**Comment by rw** [comment]
@Centril What do you think about creating an auxiliary builder struct type to be used just for playing nice with Arbitrary?

```rust

#[derive(Arbitrary)]
struct MyStructArbitraryBuilder {
  items: [Vec<u8>; 10],
}

impl MyStructArbitraryBuilder {
    fn to_my_struct(self) -> MyStruct {
        // ...
    }
}
```

I don't think this is composable with derive, and I'm not sure how to implement length limits in the Vec, but it could be a start.

I wonder if there would be a benefit to creating builder types like this, in general? So that I could create a Builder type for, say, MyArrayVec and deriving Arbitrary would be parameterized by a type that implements Builder<MyArrayVec>.

**Comment by Centril** [comment]
`[Vec<u8>; 10]` seems semantically different tho? That will always generate 10 arrays with vectors of arbitrary size (within limits but details...). So indeed, I don't see how you can make that into `ArrayVec<[u8; 16]>` without doing some hacky discarding (but that will also be doing extra work for no gain). I think it's better/cleaner to dig into the `impl<...> Arbitrary for Vec<T>` code and extract the relevant logic. Perhaps we can add an `arrayvec` optional dependency for proptest?

> I wonder if there would be a benefit to creating builder types like this, in general? So that I could create a Builder type for, say, MyArrayVec and deriving Arbitrary would be parameterized by a type that implements Builder.

The derive stuff for `Arbitrary` is able to bake in custom strategies via functions and whatnot so you can reduce some of the boilerplate that way.

**Comment by rw** [comment]
@Centril Happy to look into the impl of Arbitrary for Vec<T> -- I looked it up but it seemed to use a lot of macros. Could you point me to the best place to start?

**Comment by Centril** [comment]
@rw The 🐰 🕳 goes as such:

- https://github.com/AltSysrq/proptest/blob/7d3310c441c634df624e30f5c7e61025cb599977/proptest/src/arbitrary/_alloc/collections.rs#L75
- https://github.com/AltSysrq/proptest/blob/7d3310c441c634df624e30f5c7e61025cb599977/proptest/src/collection.rs#L194-L216
- https://github.com/AltSysrq/proptest/blob/7d3310c441c634df624e30f5c7e61025cb599977/proptest/src/collection.rs#L532-L672

**Comment by rw** [comment]
@Centril Hmm, is it enough to do:

```rust
 impl_1!(MyArrayVec, VecStrategy, => vec); 
```

?

**Comment by Centril** [comment]
The macro isn't public but even so that would generate a `Vec<T>`. If you are OK with that then you can just map a `Vec<u8>` bounded at `[0, 16)` elements to an `ArrayVec<[u8; 16]>` . The only drawback would be unnecessary allocation.

**Comment by rw** [comment]
@Centril Thanks! Would you be able to help me write this impl? I don't understand everything involved, nor what the `impl_1` macro is doing.

**Comment by Centril** [comment]
I would suggest forgetting about `impl_1` right now and focusing on the basics.
You can make a strategy for `ArrayVec<[T, u16]>` with:

```rust
use proptest::strategy::Strategy;

fn gen_array_vec<T>(elem: impl Stategy<Value = T>) -> impl Stategy<Value = ArrayVec<[T; 16]>> {
    proptest::collection::vec(elem, 0..=16).prop_map(|vec| vec.collect())
}
```

Then, if you want to avoid the additional work, I would read up on the `VecStrategy` logic and implement a strategy for `ArrayVec<[T; $n]>` elements where `$n:expr` is ideally from a macro (due to no const_generics...).

**Comment by bluss** [comment]
Why is an impl needed? I thought the point was value based and not type based testing :)

**Comment by Centril** [comment]
@bluss well, ever since `Arbitrary` was added it's both value (at its core) and type based for added convenience (oftentimes you do have a canonical strategy for a type).

**Comment by rw** [comment]
@bluss I have opinions, but I'm not an expert on this library yet. From what I can tell, implementing Arbitrary is useful when you want to use proptest-derive, among other things.

@Centril WDYT about creating a helper function to turn a Strategy into an impl of Arbitrary? I'm finding that I don't know which combinators to use to create the associated types for Arbitrary. I feel that this library has a big DSL that takes some time to learn. Maybe we can provide a shorter happy path for this common case. (I think I understand the value proposition of the proptest library, and I'm hoping to learn more, but right now I hope to get unblocked without needing to grok everything.) Thanks!

**Comment by rw** [comment]
For future readers: I figured this out by creating "builder" types that are used just for testing purposes. I didn't figure out how to manually implement Arbitrary myself for my own types.

Here's an example of the kind of code I wrote:

```rust
#[derive(Arbitrary)]
struct MyStructSimple {
  items: [[u8; 16]; 10],
}

impl MyStructSimple {
  fn to_actual(&self) -> MyStruct {
    unimplemented!()
  }
}

struct MyStruct {
  items: [MyArrayVec; 10],
}

proptest! {
  #[test] 
  fn test(input in any::<MyStructSimple>) {
    let actual = input.to_actual();
    assert_eq!(actual.items[0][0], 123);
  }
}
```
