### ISSUE TITLE
Release proptest-derive 0.2.0?

### ISSUE THREAD

**Issue by sunshowers** [AltSysrq/proptest#196]
Thanks for releasing proptest 0.10!

Looks like `proptest-derive` needs to be updated as well. It'll be a breaking change because of the `TupleUnion` stuff, any chance you could release a version 0.2.0? Thanks!

**Comment by AltSysrq** [comment]
I didn't think it was necessary since `proptest` is only a dev-dependency.

**Comment by sunshowers** [comment]
hmm, at the moment code that uses proptest-derive doesn't compile against proptest 0.10 because it generates output incompatible with 0.10.

I think they're both tightly coupled, such that a specific major version of proptest-derive only works with one version of proptest. It might be worth bumping proptest-derive all the way to 0.10.

**Comment by AltSysrq** [comment]
That seems odd, since the tests for `proptest-derive` do test against whatever's in the repo and they pass there, so if there is a problem it's a gap in the test coverage. I'll look into this tomorrow evening.

**Comment by sunshowers** [comment]
right, proptest-derive in master works well but the version on crates.io, 0.1.2, doesn't :)

**Comment by sunshowers** [comment]
Thinking about this more, it may make sense to expose the derive as an optional feature in proptest, similar to how crates like `serde` do it. That way you're guaranteed to get a derive proc-macro that matches the version of proptest in use.

**Comment by AltSysrq** [comment]
> right, proptest-derive in master works well but the version on crates.io, 0.1.2, doesn't

Oh right, lack of sleep must have gotten to me. 0.2.0 published.
