### ISSUE TITLE
Generating a chain of values

### ISSUE THREAD

**Issue by cloudhead** [AltSysrq/proptest#198]
Hey there, I can't figure out for the life of me how to generate a chain of values, where each value is generated based on the previous value. Think of a commit history for example, where each commit has the hash of the parent commit, eg.:

```
vec![Commit { hash: 123, parent: 0 }, Commit { hash: 4328, parent: 123 }, Commit { hash: 188, parent: 4328 }, Commit { hash: 5418, parent: 188 }, ...]
```

I looked into `prop_recursive` as well as `prop_flat_map`, but can't seem to figure out how to achieve this.

**Comment by AltSysrq** [comment]
This sort of thing needs to be approached a bit indirectly.

If what you actually need is just a chain where each element has a particular value from the previous, you can have proptest generate a sequence of values (either with dummy values that need to be replaced later, or a different type with just the fields proptest generates) and then use `prop_map` to fill those references in. Here's a simple example of doing that:

```rust
use proptest::prelude::*;

#[derive(Debug)]
struct Commit {
    hash: u32,
    parent: u32,
}

fn commit_chain() -> impl Strategy<Value = Vec<Commit>> {
    // Have proptest generate 10 commit hashes
    let commit_hashes = proptest::collection::vec(
        proptest::num::u32::ANY,
        10);
    // Then map them into the chain of values
    commit_hashes.prop_map(|hashes| hashes.into_iter().scan(0, |acc, hash| {
        let parent = *acc;
        *acc = hash;
        Some(Commit { hash, parent })
    }).collect::<Vec<_>>())
}

fn main() {
    // Manually generate some values to demonstrate
    use proptest::strategy::ValueTree;
    use proptest::test_runner::TestRunner;

    let mut runner = TestRunner::default();
    let strategy = commit_chain();
    println!("{:?}", strategy.new_tree(&mut runner).unwrap().current());
}
```

If the _way in which values are generated_ needs to depend on the previous value, things are a lot more difficult. `prop_flat_map` is what you need (or `prop_ind_flat_map` for better speed), in combination with use of `Strategy::boxed` to prevent the types from blowing up as you nest them (either by a recursive function or in a loop).

**Comment by cloudhead** [comment]
Thanks, it is the later I guess that I want, eg. in the commit history example, the value of the previous commit needs to be known to compute its hash, and thus the next value (commit). However, since it's just a field, *maybe* there's a way to generate the list first, and fill in the hashes later (though I'm not sure that's of much help).

It's definitely a recursive structure.

I think this might be one of the few cases where `quickcheck` is a better choice, so I might just go for that :thinking:

Thanks for your time!
