### ISSUE TITLE
How do I use HashMapStrategy? Documentation unclear, has no examples.

### ISSUE THREAD

**Issue by dyc3** [AltSysrq/proptest#204]
Usage of HashMapStrategy is unclear from the documentation. I need to randomly create hashmaps that meet certain conditions. From what I can see, I'm supposed to supply it with 2 other strategies to generate the keys and the values, but I'm not exactly sure how I'm supposed to make the SizeRange. Should I even be using the `hash_map` function?

Related documentation:

https://docs.rs/proptest/0.10.0/proptest/collection/fn.hash_map.html
https://docs.rs/proptest/0.10.0/proptest/collection/struct.HashMapStrategy.html

**Comment by Centril** [comment]
`HashMapStrategy` is literally a thin wrapper around a strategy for creating `Vec<(Key, Value)>` up to the specified size and filtered to not go below the minumum.

So if you e.g., use `hash_map(key_strat, val_strat, 5...10)`, then what happens is that a `vec((key_strat, val_strat), 5..10)` is created, and then this is mapped using [`vec.into_iter().collect()`](https://docs.rs/proptest/0.10.0/src/proptest/collection.rs.html#476-482), giving you a `HashMap` of `5..10` elements with keys drawn from `key_strat` and values from `val_strat`.

Note that most `RangeXYZ` types implement `Into<SizeRange>`, which is what `hash_map` accepts, so you can use the normal Rust range syntax.

I hope that answers your question.

**Comment by dyc3** [comment]
Ah, I see. Can I use prop_filter on it? or do I just have to ignore values I can't use?

**Comment by Centril** [comment]
Sure, you can use `.prop_filter` on the `key_strat`, `value_strat`, or the final `hash_map(...)` strategy. Doing so on the latter will give you a `&HashMap<K, V>` which you can apply a predicate to. You can also ignore irrelevant maps in each test itself as well, but that will scale less well if the strategy is used a lot. If you can create a correct key/value/map by construction, then that is preferable to filtering (see the book / docs on `prop_filter` for elaboration).

**Comment by dyc3** [comment]
Thanks for your help! Closing...
