### ISSUE TITLE
Saving regressions automatically and/or adding explicit tests easily

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#21]
This is being discussed over at quickcheck in issues (I'll let those discussions explain):
+ https://github.com/BurntSushi/quickcheck/issues/130
+ https://github.com/BurntSushi/quickcheck/issues/40

It would be neat to add something similar for proptest =)
Something like:

```rust
#[proptest_save(path/to/my/regressions)]
```

Obviously the type tested has to be serializable somehow.

```rust
#[proptest_explicit(regression1, regression2, ...)]
```

**Comment by AltSysrq** [comment]
Oooh, this is a very interesting idea. I'm going to make a pass at this this weekend.

**Comment by Centril** [comment]
If you want to brainstorm on ideas I'm always (kinda) available at #rust @ irc.mozilla.org - I also created a channel #rust-test for discussion on testing & rust =)

**Comment by AltSysrq** [comment]
[Added in 0.3.3](https://docs.rs/proptest/0.3.3/proptest/#failure-persistence)
