### ISSUE TITLE
Difficulties using the prop_oneof macro

### ISSUE THREAD

**Issue by mpizenberg** [AltSysrq/proptest#211]
Hi, I'm trying to setup property testing on some of my code and having trouble using `prop_oneof!`. I have a module, called `range`, in which I defined a `strategy` function for a `Range` type of mine like so:

```rust
// range module
#[cfg(test)]
pub mod tests {
    pub fn strategy() -> impl Strategy<Value = Range<usize>> {
        prop::collection::vec(any::<usize>(), 0..10).prop_map(...)
    }
}
```

I did it like this because I'm quite new to proptest and didn't figure out how to implement `Strategy` directly for `Range`. But it's working very well for my tests.

Now the issues comes from trying to do similar things with the `prop_oneof!` macro. In another module, called `term`, I've also tried to defined a similar function:

```rust
// term module
pub enum Term<V> {
    Positive(Range<V>),
    Negative(Range<V>),
}

#[cfg(test)]
pub mod tests {
    pub fn strategy() -> impl Strategy<Value = Term<usize>> {
        crate::range::tests::strategy().prop_map(|range| {
            prop_oneof![Term::Positive(range.clone()), Term::Negative(range)].boxed()
        })
    }
}
```

Unfortunately this does not compile, apparently because `Term` does not implement `Strategy`. Is there a way to solve this? If not and I'm forced to implement Strategy on Term, is there a simple guide somewhere on how to do that? I got a bit lost in the associated types when I tried.

**Comment by Eh2406** [comment]
I just reread this section: https://altsysrq.github.io/proptest-book/proptest/tutorial/enums.html

I think you are looking for `Just` a Strategy that always returns its argument.
```rust
            prop_oneof![Just(Term::Positive(range.clone())), Just(Term::Negative(range))].boxed()
```

**Comment by mpizenberg** [comment]
Sorry, I'm just realizing I reversed the `prop_oneof` and map ... sorry :(
This is actually working:
```rust
    pub fn strategy() -> impl Strategy<Value = Term<NumberVersion>> {
        prop_oneof![
            crate::range::tests::strategy().prop_map(|range| Term::Positive(range)),
            crate::range::tests::strategy().prop_map(|range| Term::Negative(range)),
        ]
        .boxed()
    }
```

**Comment by mpizenberg** [comment]
> I just reread this section: https://altsysrq.github.io/proptest-book/proptest/tutorial/enums.html
> 
> I think you are looking for `Just` a Strategy that always returns its argument.
> 
> ```rust
>             prop_oneof![Just(Term::Positive(range.clone())), Just(Term::Negative(range))].boxed()
> ```

I've just (pun intended ^^) tried and it does not seem to work with the `Just`. I'm wondering if it's still possible to factor that `prop_map` but since now it's working I'm closing the issue. I usually don't want to create noisy issues so waited since yesterday to let the problem sink in for the night. I can't believe it took me 2 min after finally posting to figure it out :facepalm: 

Thanks anyway! closing the issue
