### ISSUE TITLE
#[derive(Arbitrary)] causes a clippy warning

### ISSUE THREAD

**Issue by KeenS** [AltSysrq/proptest#227]
Running clippy against this code generates following warning

```rust
use proptest_derive::Arbitrary;

#[derive(Debug, Arbitrary)]
struct User {
    id: i32,
}

fn main() {}
```

```console
$ cargo clippy -- -Wclippy::all
    Checking proptest-clippy v0.1.0 (/home/shun/Rust/proptest-clippy)
warning: passing a unit value to a function
 --> src/main.rs:5:5
  |
5 |     id: i32,
  |     ^^
  |
  = note: `-W clippy::unit-arg` implied by `-W clippy::all`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg
help: move the expression in front of the call and replace it with the unit literal `()`
  |
5 |     {
6 |         Arbitrary;
7 |         id
8 |     }: i32,
  |

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
```

This is too noisy. Is there any chance to address this issue in the library side?

Note that adding `#[allow(clippy::unit_arg)]`  to the type doesn't solve this problem because the warning is from the generated code.  One (cumbersome) way to silence this warning in user side is  wrapping the definition with `mod` and allow all lints inside the `mod`:

```rust
mod types {
    #![allow(clippy::all)]

    use super::*;
    #[derive(Debug, Arbitrary)]
    pub(super) struct User {
        pub(super) id: i32,
    }
}
```

Though the warning can be silenced by the method above, it would be grateful if the derive macro generates that code.

**Comment by mikerite** [comment]
A Clippy bug has already been logged for this. rust-lang/rust-clippy#6594

Personally, I wouldn't add work arounds for Clippy bugs.

**Comment by KeenS** [comment]
Then I'll watch that issue. Thank you.
