### ISSUE TITLE
Shrink given case

### ISSUE THREAD

**Issue by hhirtz** [AltSysrq/proptest#231]
Is it possible to give proptest known, problematic input so that it can shrink it to a minimal case?

**Comment by Centril** [comment]
Yes, it's doable.

To do so, you must first obtain a [`vt: ValueTree`](https://docs.rs/proptest/1.0.0/proptest/strategy/trait.ValueTree.html) representing the problematic input, and the algorithm for how to shrink it. Once you have the `vt`, you can use https://docs.rs/proptest/1.0.0/proptest/test_runner/struct.TestRunner.html#method.run_one to shrink it.

Now, whether this is easy depends on how hard it will be to construct your `ValueTree` implementation. Maybe there's a suitable one already for your type.

**Comment by hhirtz** [comment]
Thank you very much, this is what I was looking for.
