### ISSUE TITLE
Arbitrary impl for OrderedFloat

### ISSUE THREAD

**Issue by Lemmih** [AltSysrq/proptest#244]
Hi, would an `Arbitrary` impl for `OrderedFloat` be more appropriate in this crate or in the `ordered-float` crate?

**Comment by Centril** [comment]
I'd say the `ordered-float` crate.

**Comment by Lemmih** [comment]
Great. I've submitted a PR to `ordered-float`.

**Comment by mbrubeck** [comment]
Added to ordered-float in https://github.com/reem/rust-ordered-float/pull/94
