### ISSUE TITLE
Having trouble with conditional compilation

### ISSUE THREAD

**Issue by nathaniel-may** [AltSysrq/proptest#245]
I have a couple of custom types that I implemented `Arbitrary` for, but I can't get the tests to both find the instance and use it when running tests if I'm using conditional compilation. I have tried all these steps on rust 1.53 and rust 1.42 with the same results.

### using `#[cfg(test)]`
I tried putting these impls behind `#[cfg(test)]` but I get the error "the trait `Arbitrary` is not implemented for `Extraction`" even though it is there, and I am running with `cargo test`.

### using `#[cfg(feature = "proptest")]`
I tried setting proptest as an optional dependency and putting these impls behind `#[cfg(feature = "proptest")]` and that compiles. However, the number of tests run from my prop test file is zero. This could mean the tests aren't being picked up by the runner, but they work without conditional compilation as they are written:

```
#[cfg(feature = "proptest")]
mod prop_tests {
    use dbt_extractor::{Extraction};
    use proptest::prelude::*;

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(100))]
    
        #[test]
        fn left_and_right_identity(x: Extraction) {
            let mempty = Extraction::new();
            assert_eq!(x, mempty.mappend(&x));
            assert_eq!(x, x.mappend(&mempty));
        }
    
        #[test]
        fn associativity(x: Extraction, y: Extraction, z: Extraction) {
            assert_eq!(
                x.mappend(&y).mappend(&z),
                x.mappend(&y.mappend(&z))
            );
        }
    }
}
```

### not using conditional compilation
If I remove all conditional compilation, both tests run as expected.

**Comment by nathaniel-may** [comment]
Looks like you can get it to work if you put all your tests in the same file that you define your impl. Sorry for the noise.

**Comment by humb1t** [comment]
Hi @nathaniel-may 👋🏻 

Actually I also stuck with this situation for a while. When I put tests into './tests' folder, meaning they are not a submodule of a crate where the type lives anymore, I can't rely on 'cfg[test]' from the crate itself, because cargo compiling it without that. What helped me to not move the tests code is this attribute on top of test function `#[cfg_attr(feature = "fuzzing", test)]
` and running tests with ` --features fuzzing` option.
