### ISSUE TITLE
Idea: Should we provide no-shrink standard definitions for `simplify` and `complicate`

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#29]
Currently, `ValueTree` is defined as:

```rust
pub trait ValueTree {
    type Value: Debug;
    fn current(&self) -> Self::Value;
    fn simplify(&mut self) -> bool;
    fn complicate(&mut self) -> bool;
}
```

Should we redefine `ValueTree` as:

```rust
pub trait ValueTree {
    type Value: Debug;
    fn current(&self) -> Self::Value;
    fn simplify(&mut self) -> bool { false }
    fn complicate(&mut self) -> bool { false }
}
```

Pros:
+ Less work in a minority of cases.

Cons:
+ Risk of users not providing custom shrinking where they should do that. (I assume this is the reason why the methods are not provided already..?)

If we elect not to do this, I think it would be good to document the choice somehow.

Right now, the strategies that do not shrink are:
+ NoShrink
+ Just
+ a potential `struct LazyJust<V: Debug, F: Fn() -> V>`
+ a potential `ClosureStrategy` for generating random functions

This seems like a short list, so the case for providing default no-shrink semantics doesn't seem very well motivated. But I'd like to bring it up so that we can document it anyways =)

**Comment by AltSysrq** [comment]
> Risk of users not providing custom shrinking where they should do that. (I assume this is the reason why the methods are not provided already..?)

Yeah, basically that, especially since the trait is next to `Strategy` where you aren't supposed to implement any of the provided methods.

I'll add a quick note to the trait that can go out with the next release. (Somehow I just now saw this issue right after having published 0.4.1…)

**Comment by AltSysrq** [comment]
Meant to tag this issue in the commit (c84ff2c), but I didn't, so linking to it via comment.

**Comment by Centril** [comment]
Great! =) Closing this as resolved then.
