### ISSUE TITLE
Suppress display of shrinking-related panics by default

### ISSUE THREAD

**Issue by flyingmutant** [AltSysrq/proptest#3]
Usually, the only thing that you are interested in is the minimal failing test case. If possible, it would be great to omit all other output.

This may very well be more of a Cargo issue though.

**Comment by AltSysrq** [comment]
The panic messages are something printed by the rust runtime library itself. As far as I know, the only way to suppress them is to [install a handler](https://doc.rust-lang.org/stable/std/panic/fn.set_hook.html), but that's process-global.

That said, maybe it's worth adding `prop_assert!`/`prop_assert_eq!` macros to make it convenient to return `Err(TestCaseError::Fail(...))` without panicking.

**Comment by flyingmutant** [comment]
Yes, I think macros are a good practical solution. There already is `prop_assume!` which is used inside properties; switching from `assert*!` to `prop_assert*!` can even make code a bit more consistent.

**Comment by AltSysrq** [comment]
Added in 0.2.1.
