### ISSUE TITLE
Only use the parts of rand we actually need wrt. winapi

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#30]
The `rand` crate recently started to use `winapi` for windows users which makes proptest slower to compile and in particular document. Since we only use `XorShiftRng`, we should not use the parts we don't need.

Also see https://github.com/rust-lang-nursery/rand/pull/241 which may be sufficient for us?
Might be a good idea to ask the rand folks if we can get `XorShiftRng` but but no other Rng we don't need =)

**Comment by AltSysrq** [comment]
Doesn't that part of `rand` come in via `rand::weak_rng()` for generating its seed (after a few levels of indirection) anyway? Ultimately seeds need to come from _somewhere_, so even in a very hypothetical extreme case were we just copied `XorShiftRng` itself into proptest and ditched `rand`, essentially the same syscall would still be needed, or alternatively a hack like seeding from the current time plus a global counter to uniquify the seeds.

**Comment by Centril** [comment]
Oh yeah:
```rust
pub fn weak_rng() -> XorShiftRng {
    thread_rng().gen()
}
```

How embarrassing, I should have checked that =P

> a hack like seeding from the current time plus a global counter to uniquify the seeds

Is that viable?

**Comment by AltSysrq** [comment]
> Is that viable?

Maybe? Though it's not something I'd particularly want to do in the context of proptest just to save a bit of compilation time (one-off at that) or documentation time (which most people won't run into since `cargo doc` doesn't include dev dependencies).

**Comment by Centril** [comment]
That sounds reasonable =) Closing this for now then.
