### ISSUE TITLE
Tracking issue: Feature parity with other libraries

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#35]
This issue is intended to be used for tracking proptest's feature parity with other property based testing frameworks in other languages and Rust.

# Python

## [Hypothesis](http://hypothesis.works/)

TODO

# Haskell

## [QuickCheck](https://hackage.haskell.org/package/QuickCheck)

TODO

## [SmallCheck](https://hackage.haskell.org/package/smallcheck)

TODO

## [Hedgehog](https://hackage.haskell.org/package/hedgehog)

TODO

## [SessionCheck](https://github.com/MaximilianAlgehed/SessionCheck)

TODO

# Erlang

## [QuiviQ QuickCheck](http://www.quviq.com/products/erlang-quickcheck/)

TODO

## [PropEr](https://github.com/manopapad/proper)

TODO

## [triq](https://github.com/krestenkrab/triq)

TODO

## [Concuerror](https://github.com/parapluu/Concuerror)

TODO

# Scala

## [ScalaCheck](https://www.scalacheck.org/)

TODO

# C++

## [RapidCheck](https://github.com/emil-e/rapidcheck)

TODO

## [CppQuickCheck](https://github.com/grogers0/CppQuickCheck)

TODO

# C

## [Theft](https://github.com/silentbicycle/theft)

TODO

# Clojure

## [test.check](https://github.com/clojure/test.check)

TODO

# Coq

TODO

## [QuickChick](https://github.com/QuickChick/QuickChick)

TODO

# F#

TODO

## [FsCheck](https://github.com/fscheck/FsCheck)

TODO

# Go

## [gopter](https://github.com/leanovate/gopter)

TODO

# Java

## [QuickTheories](https://github.com/NCR-CoDE/QuickTheories)

TODO

# JavaScript

## [jsverify](https://github.com/jsverify/jsverify)

TODO

# PHP

## [Eris](https://github.com/giorgiosironi/eris)

TODO

# Ruby

## [Rantly](https://github.com/abargnesi/rantly)

TODO

# Swift

## [Swiftcheck](https://github.com/typelift/SwiftCheck)

TODO

# OCaml

## [OCaml QuickCheck](https://github.com/camlunity/ocaml-quickcheck)

TODO

**Comment by AltSysrq** [comment]
I do not consider it a goal of proptest to have feature parity with literally every property testing library under the sun, particularly not the QC family since the paradigm is quite different.

I also don't see a "tracking issue" being useful for this since users wouldn't care about when total feature parity was reached, but rather individual features which would be their own issues anyway. I.e., this is redundant with the issues list and a "feature" tag, which I guess I'll go and create now.

Closing this issue to reduce clutter.

**Comment by Centril** [comment]
Oh; the intent was not that we have feature parity, but to rather be able to make informed decisions about what exists out there and if we want it or not =)

**Comment by Centril** [comment]
Do you mind if I keep filling in things here as I review the different libraries to see if there is something that fits us? We can keep the issue closed as I do that =)

**Comment by AltSysrq** [comment]
Might as well I guess
