### ISSUE TITLE
exporting Rng may have caused other problems (sorry)

### ISSUE THREAD

**Issue by vitiral** [AltSysrq/proptest#37]
after updating proptest I'm getting this error:

```
error[E0277]: the trait bound `R: rand::Rng` is not satisfied
  --> src/test/implemented.rs:43:9
   |
43 |         regex_generate::Generator::parse(r"\.([a-zA-Z0-9_]{1,10})", rng.clone()).unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand::Rng` is not implemented for `R`
   |
   = help: consider adding a `where R: rand::Rng` bound
   = note: required by `regex_generate::Generator`

```

I'm trying to trace down what is going wrong, but it seems like `extern crate rand; rand::Rng` is being treated differently than `proptest::Rng`, even though they are the _same version_. I'm not totally sure what's going on

**Comment by AltSysrq** [comment]
Hm, would you be able to upload your `Cargo.lock` file?

**Comment by vitiral** [comment]
The error occurs at this branch in the `artifact-data/` directory (it is a sub-crate of my main `artifact` project)

https://github.com/vitiral/artifact/tree/data/artifact-data

**Comment by vitiral** [comment]
The `Cargo.lock` is here: https://github.com/vitiral/artifact/blob/data/artifact-data/Cargo.lock

**Comment by vitiral** [comment]
hmm... removing the `Rand` export in proptest doesn't seem to be changing anything. I've also tried not pinning the version of `rand` -- also didn't work...

**Comment by vitiral** [comment]
oh I'm an idiot. The issue is that `regex_generate` is now using a different version of `rand` -- it has nothing to do with proptest!

**Comment by vitiral** [comment]
Actually, proptest::prelude::Rng helped me diagnose this -- so I think it is totally worth keeping.
