### ISSUE TITLE
Recursive strategies do not shrink by depth as "expected"

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#42]
While trying to improve the definition of `Strategy for Recursive<..>` in PR #40 I later realized that `IndFlatten` was being used, so the input strategy (`bool::Weighted`) is never shrunk, and so the depth of a recursive type is never shrunk as "expected" (at least by users of QuickCheck in asorted languages?). In other words, the following test holds:

```rust
#[test]
fn test_recursive_depth_shrink() {
    #[derive(Clone, Debug)]
    enum Nat { Z, S(Box<Nat>) }
    impl Nat {
        fn size(&self) -> usize {
            if let Nat::S(ref nat) = *self { 1 + nat.size() } else { 0 }
        }
    }

    let strat = Just(Nat::Z).prop_recursive(4, 1, 1,
        |strat| strat.prop_map(|nat| Nat::S(Box::new(nat)))
    );

    let mut runner = TestRunner::default();
    for _ in 0..::std::u16::MAX {
        let mut vt = strat.new_value(&mut runner).unwrap();
        let curr = vt.current().size();
        while vt.simplify() {}
        assert_eq!(curr, vt.current().size());
    }
}
```

while you could reasonably expect that the following should hold instead:

```rust
        let mut runner = TestRunner::default();
        for _ in 0..::std::u16::MAX {
            let mut vt = strat.new_value(&mut runner).unwrap();
            while vt.simplify() {}
            assert_eq!(0, vt.current().size());
        }
```

that is, if you shrink a `Nat` maximally, you should always end up with `0` as size (which is the same as the depth in this case).

We could of course change `IndFlatten` to `Flatten` in which case it does hold, but then you get into `complicate_regen_remaining` and such...

I think in any case, we should document the shrinking behavior that is used... But is the current behavior right?

**Comment by AltSysrq** [comment]
Thanks for bringing this to my attention. I think `prop_recursive()` predates unions supporting weights, so it had an inline implementation of `IndFlatten` that was later changed to `IndFlatten` itself.

As of 0.5.1, it uses `prop_oneof!` with weights , so it now shrinks correctly.
