### ISSUE TITLE
Feature: Strategy for Option<T> and Result<T, E>

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#5]
It would be nice to add strategies for `Option` and `Result<T, E>`.

While it's doable with `Union`, leaner and more performant implementations are possible...

A possible implementation for `Option` is:

```rust
pub fn optional<T: Strategy>(strat: T) -> OptionStrategy<T> {
    optional_weighted(strat, 0.5)
}

pub fn optional_weighted<T: Strategy>(strat: T, prob: f64) -> OptionStrategy<T> {
    OptionStrategy { strat, prob }
}

#[derive(Clone, Debug)]
pub struct OptionStrategy<T: Strategy> {
    strat: T,
    prob: f64,
}

impl<T: Strategy> Strategy for OptionStrategy<T> {
    type Value = OptionValueTree<T::Value>;

    fn new_value(&self, runner: &mut TestRunner) -> Result<Self::Value, String> {
        Ok(OptionValueTree {
            prev: None,
            pick:
                if weighted(self.prob).new_value(runner)?.current() {
                    Some(self.strat.new_value(runner)?)
                } else {
                    None
                }
        })
    }
}

#[derive(Clone, Debug)]
pub struct OptionValueTree<T: ValueTree> {
    pick: Option<T>,
    prev: Option<T>,
}

impl<T: ValueTree> ValueTree for OptionValueTree<T> {
    type Value = Option<T::Value>;

    fn current(&self) -> Self::Value {
        self.pick.as_ref().map(ValueTree::current)
    }

    fn simplify(&mut self) -> bool {
        self.pick.take().map_or(false, |mut inner| {
            if inner.simplify() {
                self.pick = Some(inner);
                self.prev = None;
            } else {
                self.pick = None;
                self.prev = Some(inner);
            };
            true
        })
    }

    fn complicate(&mut self) -> bool {
        if let Some(pick) = self.prev.take() {
            self.pick = Some(pick);
            true
        } else {
            self.pick.as_mut().unwrap().complicate()
        }
    }
}
```

**Comment by AltSysrq** [comment]
Thanks for the suggestion; this is something I had meant to add but forgot about.

> leaner and more performant implementations are possible

Do you see a case where the performance difference would be significant? I'd be more inclined to just make `Union` support weights and then just have a simpler frontend to that, at least at first.

In any case, I will most likely be able to look into implementing these this weekend.

**Comment by Centril** [comment]
> Do you see a case where the performance difference would be significant? 

I guess that depends on how many tests you have and how many `Option`s your data structures have - if you have a lot, marginal constant factors will still cause significant delay - so if it can be reduced - why not? In any case, while premature optimization is bad, so is intentional pessimization.
Using `Union`, you always get heap allocation and more complex logic - this should be more expensive than the (smaller) stack allocation of a specialized implementation.

> I'd be more inclined to just make Union support weights and then just have a simpler frontend to that, at least at first.

I think the most important part is to have the functions like `optional` and `optional_weighted` since that is the user facing API.

I'd still recommend having two dedicated types `OptionStrategy<T: Strategy>, ResultStrategy<T: Strategy, E: Strategy>` instead of returning `Union<T: Strategy>` because then you are free to change the internal implementation of these types to just wrap `Union` if you wish without breaking changes.

Adding weights to `Union` in addition sounds like a terrific idea.

**Comment by AltSysrq** [comment]
Fair enough, I think you've convinced me.

**Comment by Centril** [comment]
Awesome =)

For the 🚲🏘️ , I think renaming `OptionStrategy` to `Optional` / `Potentially` / `Perhaps` / `Possibly` and `ResultStrategy` to `Resulting` is a good idea since none of the current strategies save for `BoxStrategy` actually has the suffix `Strategy` in it, so it would be more consistent to not add the suffix for the new ones.

**Comment by AltSysrq** [comment]
These are now in 0.3.0. The code for `Option` goes through a general `TupleUnion` which should produce reasonably efficient code (not quite optimal due to some extra bookkeeping, but there's no allocation or virtual dispatch). `prop_oneof!` also uses this when possible now.

> none of the current strategies save for BoxStrategy actually has the suffix `Strategy`

There was actually already `VecStrategy` and `CharStrategy`, and the only reason there wasn't more was due to the rest of the `collection` module using `BoxedStrategy` instead of unique types.

The convention I seem to have settled on is to use `FooStrategy` if there's nothing to say about it other than a "strategy that generates foos" but otherwise using a unique name. So the new types are `OptionStrategy` and `MaybeOk`/`MaybeErr`. Probably not the best, but it's consistent enough I guess.
