### ISSUE TITLE
Simplify usage with impl Trait

### ISSUE THREAD

**Issue by Marwes** [AltSysrq/proptest#50]
Now that `impl Trait` is on stable rust I started changing all the strategy functions to return `impl Strategy` instead of `BoxedStrategy`. The good news is that it just works but with a small caveat which makes it a bit awkward to use.

Since `Strategy` only indirectly specifies the `Value` through the associated `ValueTree` one must write the return type like below which is rather counter-intuitive and verbose.

```rust
impl Strategy<Value = impl ValueTree<Value = Vec<String>>>
// Nicer if this would be the type
impl Strategy<Value = Vec<String>>
```

I don't know enough about the internals of proptest to say how this could be fixed though but perhaps it would be possible to specify the `Value` on `Strategy` in a similar manner to how [IntoIterator](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html) does it? Or maybe there is a simpler way to do it than that even.

Great library in either case though! :)

**Comment by AltSysrq** [comment]
> a similar manner to how IntoIterator does it

I think this will work; thanks for the suggestion! It'll be a breaking change, but probably worth it and the stabilisation of `impl Trait` was expected to be an occasion for breaking changes anyway.

Appologies for the delayed response, I was travelling the past few days.

**Comment by Centril** [comment]
I've implemented this (and other things..) in a branch; not fully done yet, but I'll create a PR soon-ish :)

**Comment by AltSysrq** [comment]
@Centril Any idea when your branch might be ready? There's a couple other things like `i128` support on stable and #54 that would be best to go out together since we'll be increasing the minimum required Rust version.

**Comment by Centril** [comment]
@AltSysrq Now. #55  -- well; semi-ready... I was hoping to do more stuff, but oh well ;)

**Comment by Centril** [comment]
This is now implemented in the `0.8.0-changes` branch so should probably close?

**Comment by AltSysrq** [comment]
I prefer not to close issues until the fix is actually generally available.

**Comment by Centril** [comment]
Aight; makes sense.

**Comment by AltSysrq** [comment]
0.8.0 is finally released, so `impl Strategy<Value = SomeType>` now works.
