### ISSUE TITLE
Idiomatic proptest approach for generating very similar repetitive properties?

### ISSUE THREAD

**Issue by ornamentist** [AltSysrq/proptest#53]
I have a Rust trait that checks compatibility of two values of the same type:

```rust
pub trait Compatible {
  fn are_compatible(x: Self, y: Self) -> bool;
}
```

I've implemented Compatible for `u8`, `u16`, `u32`, `u64`, `usize`, as well as the signed integer types and `f32`, `f64`. I'd like to create proptest properties for `are_compatible()` for all fourteen implementations of Compatible.  

To avoid a lot of repeated code my first thought was to create a macro to generate the properties but ran into problems with nested macro expansion in Rust. Another idea was to create just one test but let proptest use `prop_oneof` at runtime to choose the type of the test pair.

Is there an idiomatic proptest-oriented way of going about this kind of repetitive testing of similar properties?

Thanks!

Stu

**Comment by AltSysrq** [comment]
I think a macro is probably your best bet. I'm not sure how `prop_oneof!` would work since each case is a different type, but putting that aside, test output is probably going to be clearer with a separate test per type rather than one test that tests all of them.

Does your "nested macro expansion" problem involve `proptest!`? If so it might just be a matter of rearranging things.

A lot of proptest's tests for this sort of thing predate the test runner, but there is [this one example](https://github.com/AltSysrq/proptest/blob/master/src/num.rs#L1162) that generates equivalent properties for `f32` and `f64` in normal `proptest!` functions.

**Comment by ornamentist** [comment]
This may be my lack of Rust macro experience showing, but I was trying this:

```rust
pub trait Compatible {
  fn are_compatible(x: Self, y: Self) -> bool;
}

impl Compatible for u8 {
  fn are_compatible(x: Self, y: Self) -> bool {
    x + y >= 100
  }
}

macro_rules! prop_compatible {
  ($scalar:ty) => {
    #[test]
    fn are_compatible(x in any::<$scalar>(), y in any::<$scalar>()) {
      Compatible::are_compatible(x, y)
    }
  };
}

proptest! {
   prop_compatible! {u8}
}
```

But Rust reports: 

error: no rules expected the token `prop_compatible`

**Comment by AltSysrq** [comment]
I see. For what you pasted, I was able to get it to compile by moving `proptest!` into the macro itself, i.e.,

```rust
macro_rules! prop_compatible {
  ($scalar:ty) => {
    proptest! {
      #[test]
      fn are_compatible(x in any::<$scalar>(), y in any::<$scalar>()) {
        Compatible::are_compatible(x, y)
      }
    }
  };
}

prop_compatible! {u8}
```

You'll also need some way to keep the test names from clashing; an easy way is to take the type as a `tt` so it can also be used as a module name, for example

```rust
macro_rules! prop_compatible {
  ($scalar:tt) => {
    mod $scalar {
      use super::*;
      proptest! {
        #[test]
        fn are_compatible(x in any::<$scalar>(), y in any::<$scalar>()) {
          Compatible::are_compatible(x, y)
        }
      }
    }
  };
}

prop_compatible! {u8}
prop_compatible! {i8}
```

**Comment by ornamentist** [comment]
Brilliant!

Hopefully when Macros 2.0 arrive we'll have a `concat_idents` macro we can use to generate unique property names with `concat_idents!(are_compatible, $scalar)`.

Thanks again.

**Comment by znewman01** [comment]
Hi! I run into the same problem basically every time I use proptest -- it corresponds exactly to how I think about properties: "any type that impl's Compatible should satisfy the 'Compatible laws.'" I'm not sure how common this is, but for me it's a daily issue :smile:  I use the macro approach for now, but it's a lot of boilerplate.

I wonder whether it might make sense to somehow associate a canonical set of tests with a trait:

```rust
trait Compatible {
  fn are_compatible(x: Self, y: Self) -> bool;
}

proptest_laws!(Compatible) {
   #[test]
   fn test_reflexive(x: Self, y: Self) {
     prop_assert_eq!(Compatible::are_compatible(x, y), Compatible::are_compatible(y, x));
   }

  #[test]
  fn test_transitive(/* ... */) { /* ... */ }
}

impl Compatible for u8 {
  // ...
}

prop::verify_laws!(Compatible, u8)
```

Implementation could be something like: `proptest_laws!(Compatilbe)` desugars to `impl VerifiableLaws for Compatible` where `VerifiableLaws` has some method that the prop test runner hooks into.

(Syntax was the first thing I thought of and might not even be valid; let's leave it aside for now.)

I want to gauge:

- is this use case (properties are associated with a trait, and verified for every type that impls the trait) as common as I think it is?
- if so, does some sugar like what I've proposed make things easier than just writing a `prop_foo!` macro for each trait?
- is the implementation I proposed (or something else obvious) reasonable?

If so, I'd definitely be interested in fleshing out such a proposal.
