### ISSUE TITLE
Why this and the *quickcheck* crate?

### ISSUE THREAD

**Issue by alexreg** [AltSysrq/proptest#59]
I'm curious: what deficiencies did you see in the *quickcheck* crate to make you create this?

**Comment by AltSysrq** [comment]
The original thing that prompted this was the difficulty in defining `Arbitrary` for a struct with a lot of fields, as well as the issue of not being able to control integer ranges on a per-item basis, both specifically [for things like this](https://github.com/AltSysrq/hexeline/blob/master/src/physics/common_object.rs#L446), which I first tried to make work with `quickcheck`, but then gave up and wrote `proptest` instead.

**Comment by alexreg** [comment]
@AltSysrq Okay, thanks for clarifying. They both look like relatively mature libraries, so I will certainly give them both a closer look!
