### ISSUE TITLE
Possible regression in 0.8.0

### ISSUE THREAD

**Issue by neoeinstein** [AltSysrq/proptest#63]
I just started using proptest in a brand new project, and after getting my first failure, subsquent runs were failing to parse the regressions file and new failures were not being added to the existing file:

During the test run, proptest output this during the test run:
```
failures:
 
---- tests::round_trip stdout ----
        proptest: /home/project/proptest-regressions/types/time/period.txt:1: unknown case type `` (corrupt file or newer proptest version?)
proptest: /home/project/proptest-regressions/types/time/period.txt:2: unknown case type `` (corrupt file or newer proptest version?)
proptest: /home/project/proptest-regressions/types/time/period.txt:3: unknown case type `` (corrupt file or newer proptest version?)
proptest: /home/project/proptest-regressions/types/time/period.txt:4: unknown case type `` (corrupt file or newer proptest version?)
proptest: /home/project/proptest-regressions/types/time/period.txt:5: unknown case type `` (corrupt file or newer proptest version?)
proptest: /home/project/proptest-regressions/types/time/period.txt:6: unknown case type `` (corrupt file or newer proptest version?)
```
The first six lines are the commented lines. It is likely due to the code [here](https://github.com/AltSysrq/proptest/blob/ba8d5f476dfde5fbd3d1442d8a66155799b33235/src/test_runner/failure_persistence/file.rs#L243), as split will return one part with the entire string if there is nothing to split on.

While I had never used proptest 0.7.2, I downgraded to that version, and using the same file, was able to create a new failure that added cases to the regressions file.

**Comment by AltSysrq** [comment]
Fixed released in 0.8.1.
