### ISSUE TITLE
Closure style invocation doesn't return closure

### ISSUE THREAD

**Issue by udoprog** [AltSysrq/proptest#66]
Hey!

Follow up from #62 and the changes done after that was merged.

Now the `proptest!` when invoked like a closure, doesn't actually return a closure. This is a bit unexpected. For example, the `move |..| {}` variant of the macro doesn't do anything special even though it might seem like it does.

Basically it runs the property test in-place, like a block statement.

This makes the thing I initially wanted to accomplish in #62 a bit more awkward, instead of:
```rust
runner.test("some test", proptest!(|..| {
    /*  */
}));
```

I now have to define an outer closure:

```rust
runner.test("some test", || {
  proptest!(|..| {
    /*  */
  })
});
```

If possible I would like to have a way that permits me to define closures with as few brackets as possible. 
If there's a need for block-style invocation, that should preferably have none-closure style syntax since it's a bit misleading.

Thanks!

**Comment by AltSysrq** [comment]
To be frank, I'm quite confused about what you're looking for now. Your original PR [called `runner.run()`](https://github.com/AltSysrq/proptest/pull/62/files#diff-54b055bccd5d65d83ac9d67346132684R691) within the macro.

> `runner.test`

Is this referring to some other test framework? If so, your example could just be written

```rust
runner.test("some test", || proptest!(|..| {
  /* ... */
}));
```

**Comment by udoprog** [comment]
Hey @AltSysrq 

> To be frank, I'm quite confused about what you're looking for now. Your original PR called runner.run() within the macro.

You are missing [this part](https://github.com/AltSysrq/proptest/pull/62/files#diff-54b055bccd5d65d83ac9d67346132684R101) which [was removed here](https://github.com/AltSysrq/proptest/commit/c85573f4ed42ea1df350ff33eb1d8737b233e3a8#diff-54b055bccd5d65d83ac9d67346132684L101). The PR had `proptest!` return a closure which you have to capture and call yourself. After that change it no longer returns a closure, it just evaluates the test _in place_.

> Is this referring to some other test framework? If so, your example could just be written.

Yes, the test framework I use captured the closure in order to execute it as part of a suite. Now there is a fair bit more bracket matching to be done because I have to wrap everything in closures manually.

**Comment by udoprog** [comment]
Ok!

> I don't think returning a closure is a good fit for a general-purpose macro here.

I think the pertinent part here is that the macro invocation _looks_ like a closure. And folks seeing it will likely expect it to _behave_ like a closure. I believe it's considered good practice to try to mimic existing language items when building macros.

If we are after something that performs in-place execution, something that doesn't look like a closure is probably more suitable, like:

```rust
proptest!((...) {
})
```

> Unless there's something else I'm missing, it seems to me that the new form is enough of a building block to just make your own convenience macro.

I already have. It's just a bummer that I have to :/.

**Comment by AltSysrq** [comment]
> the macro invocation looks like a closure

I guess we have different ways of looking at things; I saw it as a function-like macro that mimics a function taking a closure as an argument. (I was wondering why you used braces though; now that makes sense.)

I suppose we'll just have to see how it plays out over time now that it's been released in its current form.

**Comment by udoprog** [comment]
Ok, let's let it settle for a while. Thanks for explaining your reasoning!
