### ISSUE TITLE
Unexpected results with "<var> in <regexp>"

### ISSUE THREAD

**Issue by AaronM04** [AltSysrq/proptest#71]
Hi, I'm working through the proptest example/tutorial at https://altsysrq.github.io/rustdoc/proptest/0.8.2/proptest/ , and I got a failure when the example says the tests should pass. The minimal failing example is `s = "00000000--"`, and `s` doesn't match the regexp `"[0-9]{4}-[0-9]{2}-[0-9]{2}"`.

What is going on here? Is this a bug?

I'm using proptest 0.8.2.

Full code:
```#[macro_use] extern crate proptest;

fn parse_date(s: &str) -> Option<(u32, u32, u32)> {
    if 10 != s.len() { return None; }

    // NEW: Ignore non-ASCII strings so we don't need to deal with Unicode.
    if !s.is_ascii() { return None; }

    if "-" != &s[4..5] || "-" != &s[7..8] { return None; }

    let year = &s[0..4];
    let month = &s[6..7];
    let day = &s[8..10];

    year.parse::<u32>().ok().and_then(
        |y| month.parse::<u32>().ok().and_then(
            |m| day.parse::<u32>().ok().map(
                |d| (y, m, d))))
}

fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_parse_date() {
        assert_eq!(None, parse_date("2017-06-1"));
        assert_eq!(None, parse_date("2017-06-170"));
        assert_eq!(None, parse_date("2017006-17"));
        assert_eq!(None, parse_date("2017-06017"));
        assert_eq!(Some((2017, 06, 17)), parse_date("2017-06-17"));
    }

    proptest! {
        #[test]
        fn doesnt_crash(s in "\\PC*") {
            parse_date(&s);
        }

        #[test]
        fn parses_all_valid_dates(s in "[0-9]{4}-[0-9]{2}-[0-9]{2}") {
            parse_date(&s).unwrap();
        }
    }
    #[test]
    fn test_unicode_gibberish() {
        assert_eq!(None, parse_date("￼ල0A 0"));
    }
}
```

**Comment by AltSysrq** [comment]
Yep, see https://github.com/AltSysrq/proptest/issues/69. It's fixed in 0.8.3.

**Comment by AaronM04** [comment]
OK, I can confirm that it's fixed if I upgrade my program to 0.8.3. I'd close this except... I want to make sure that others don't blindly copy-paste the 0.8.2 version into their Cargo.toml as I did. I don't remember how I got to this link: https://altsysrq.github.io/rustdoc/proptest/0.8.2/proptest/ Is it something that other people would stumble upon?

If so, I can make a PR to fix the docs.

**Comment by AltSysrq** [comment]
> copy-paste the 0.8.2 version into their Cargo.toml

Unless you already have 0.8.2 in `Cargo.lock`, cargo will actually get the latest 0.8.x given `proptest = "0.8.2"` since it's intererpted as `^0.8.2`, i.e., "anything semver-compatible with 0.8.2".

> I don't remember how I got to this link

I would assume you got it from the link on crates.io before 0.8.3 was uploaded. It could be worth adding a brief note in the rustdoc version to double-check that it's the latest version though.

**Comment by AltSysrq** [comment]
The script used to generate the github.io pages now adds a note to the docs for older versions that they are not the latest. See for example the [0.8.4 docs](https://altsysrq.github.io/rustdoc/proptest/0.8.4/proptest/).
