### ISSUE TITLE
Misleading example in README?

### ISSUE THREAD

**Issue by boustrophedon** [AltSysrq/proptest#74]
I'm not sure if this is intentional, but it seems to me that the example given in https://github.com/AltSysrq/proptest#limitations-of-property-testing will always pass, not "virtually always". 

```rust
proptest! {
    #[test]
    fn i64_abs_is_never_negative(a in any::<i64>()) {
        assert!(a.abs() >= 0);
    }
}
```

If you want an example that misses a corner case, it should be > 0 so that in the rare event a is 0, the test fails. Otherwise, the example is kind of confusing.

Also, I think this library is pretty neat.

**Comment by boustrophedon** [comment]
Hahaha you got me! I didn't consider how the asymmetry of the range of signed integers gets handled. Maybe add a note/give a hint as to why that test will fail then?

**Comment by AltSysrq** [comment]
Good idea, added a comment.
