### ISSUE TITLE
Incorrect documentation on float_to_weight

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#78]
The documentation on [`float_to_weight`](https://altsysrq.github.io/rustdoc/proptest/latest/proptest/strategy/fn.float_to_weight.html) states that it:
> Panics if f is negative, greater than 1.0, or NaN.

But the code states:

```rust
assert!(f > 0.0 && f < 1.0, "Invalid probability: {}", f);
```

so either the documentation is wrong (i.e: it panics if greater than or equal to 1.0) or the code is wrong.

**Comment by AltSysrq** [comment]
The documentation is wrong since the internals require the integer weight to be in `1..WEIGHT_BASE`. I'll fix it in the next version which will probably be soon due to the nightly breakage.
