### ISSUE TITLE
Contract breaking impl From<SizeRange> for Range<usize>

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#80]
A while back I added [the implementation](https://github.com/AltSysrq/proptest/blob/master/src/collection.rs#L124-L131):

```rust

/// Given a size range `[low, high]`, then a range`low..(high + 1)` is returned.
/// This will panic if `high == usize::MAX`.
impl From<SizeRange> for Range<usize> {
    fn from(sr: SizeRange) -> Self {
        let (start, end) = sr.extract();
        start..end + 1
    }
}
```

however, the trait `From` [states that](https://doc.rust-lang.org/nightly/std/convert/trait.From.html):
> Note: this trait must not fail.

Therefore, the implementation above is contract breaking since it may panic in fringe circumstances.
As such, the implementation should be removed. This amounts to a breaking change (so we should probably label the issue as such...)

**Comment by AltSysrq** [comment]
I doubt anyone is actually using this or will do so in the near future since proptest doesn't ever return this type on its own, so it would require someone else to decide to use `SizeRange` themselves and then go back into a range. I agree it should be removed eventually, but I'm inclined to wait for the next breaking changes train.

**Comment by Centril** [comment]
> I agree it should be removed eventually, but I'm inclined to wait for the next breaking changes train.

Yeah; I agree with everything you said and this :)

I would suggest that we start with a more elaborate labeling system in this repo with milestones and more labels, which will be more important as proptest grows in importance in the ecosystem (which I'm hoping it will, because I think it is the state of the art wrt. Rust and testing). Something like:

+ E-easy
+ E-medium
+ E-hard
+ E-help-wanted
+ P-high
+ P-low
+ breaking-change

and so on...

Here's some inspiration:

+ https://github.com/dtolnay/syn/labels
+ https://github.com/rust-random/rand/labels
+ https://github.com/SergioBenitez/Rocket/labels

**Comment by Centril** [comment]
Seems I implemented that incorrectly; should be:

```rust
/// Given `low .. high`, then a size range `[low, high)` is the result.
impl From<Range<usize>> for SizeRange {
    fn from(r: Range<usize>) -> Self {
        let end = if r.end == 0 { 0 } else { r.end - 1 };
        size_range(r.start..=end)
    }
}
```

This can only occur if you provide `forall x: usize. (x..0)`.

**Comment by Eh2406** [comment]
Or you can use `saturating_sub`, in fact that could be a good mitigation or this entire thing.

**Comment by Centril** [comment]
@Eh2406 if you do `r.start..=r.end.saturating_sub(1)` then you may still reach cases like `0..0` becoming `0..=0` which is now 1 element more.

**Comment by AltSysrq** [comment]
> I just hit a related case

Fixed in 0.8.6, along with some other issues with `subsequence`.

The original issue this report is about no longer happens as of 0.8.6 since `Range` is now used as the internal representation (in exchange for simply not allowing `usize::MAX` to be an included value at all).

**Comment by AltSysrq** [comment]
(I'm going to keep this open for the moment since there are some other unaddressed talking points still.)

**Comment by AltSysrq** [comment]
Removed the `impl`s in question in 0.9.0.
