### ISSUE TITLE
How do I generate byte buffers by regexes?

### ISSUE THREAD

**Issue by vi** [AltSysrq/proptest#83]
Is three [`regex::bytes`](https://docs.rs/regex/1.0.2/regex/bytes/index.html) analogue for proptest?

**Comment by AltSysrq** [comment]
There is, generating `Vec<u8>`: https://altsysrq.github.io/rustdoc/proptest/0.8.4/proptest/string/fn.bytes_regex.html

**Comment by vi** [comment]
Shall it be more visible in documentation, e.g. searchable by "bytes" keyword in README?

**Comment by AltSysrq** [comment]
You can find it by searching for "bytes" in the search bar at the top of the API docs. Since it's not one of the more commonly used strategies I do not feel it is worth further expanding the already large readme just to call it out.
