### ISSUE TITLE
Question: prop_oneof multiple any types for vec

### ISSUE THREAD

**Issue by SephVelut** [AltSysrq/proptest#94]
Given this strategy producer function
```
fn generate_stuff<T>(b: Range<T>, len: Range<usize>) -> BoxedStrategy<Vec<T>>
            where Range<T>: Clone + Strategy<Value = T>,
                  T: Debug + Clone + 'static
        {
            prop::collection::vec(b, len)
                .prop_flat_map(|vec| {
                    Just(vec)
                })
                .boxed()
        }
```

I want to produce vectors of type u8, i16, u16, i32 etc.. Randomly over a sequence of tests. I thought this would work

```
proptest! {
            #[test]
            fn test(s in prop_oneof![
                    generate_stuff(Range{start: -127i16, end: 127i16}, 1..11),
                    generate_stuff(Range{start: 0u8, end: 2u8}, 1..11)
                ]) {
....
....
```

Errors out `type mismatch resolving <proptest::strategy::BoxedStrategy<std::vec::Vec<u8>> as proptest::strategy::Strategy>::Value == std::vec::Vec<i16>`

What the examples for prop_oneof used `prop::num::i16::ANY` and `prop::num::u32::ANY` made me think I could get away with different typed vectors as well. Removing the second generate_stuff() using u8 allows it to work, but that's not the point. Am I missing something?

**Comment by SephVelut** [comment]
I see. For some reason I thought prop_oneof! was doing some return type juggling, the kind of which I've seen before in crates. This is what I've ended up doing:

```
#[derive(Clone, Debug)]
        enum SomeVec {
            U8(Vec<u8>),
            I16(Vec<i16>)
        }

        enum SomeRange {
            U8(Range<u8>),
            I16(Range<i16>),
        }

        fn generate_audio(range: SomeRange, len: Range<usize>) -> BoxedStrategy<SomeVec> {
            match range {
                SomeRange::U8(t) => {
                    prop::collection::vec(t, len)
                        .prop_flat_map(|vec| {
                            Just(SomeVec::U8(vec))
                        })
                        .boxed()
                },

                SomeRange::I16(t) => {
                    prop::collection::vec(t, len)
                        .prop_flat_map(|vec| {
                            Just(SomeVec::I16(vec))
                        })
                        .boxed()
                }
            }
        }
```

Seems like I have to use SomeRange and pattern match, since eventually, Just() has to take a concrete type and not a type param I can generalize in the function definition with a generic like `Range<T>`.

Out of curiosity, what would you do? You want to generate vector data over a set of general integer types, to be used randomly by proptest in its many iterations of a test function.

**Comment by Centril** [comment]
For now, I would just write a macro taking a type:

```rust
fn generate_stuff<T>(b: Range<T>, len: Range<usize>) -> BoxedStrategy<Vec<T>> {
    ...
}

macro_rules my_test! {
    ($testname:ident, $typ: ty) => {
        proptest! {
            #[test]
            fn test(s in generate_stuff::<$typ>(...)) {
                ...
            }
        }
    }
}

my_test!(the_u8_test, u8);
my_test!(the_i16_test, i16);
```
