### ISSUE TITLE
timeout option giving up?

### ISSUE THREAD

**Issue by Eh2406** [AltSysrq/proptest#95]
While trying to debug why https://github.com/rust-lang/cargo/pull/5921 is timing out on CI, I tried adding a value for the `timeout` option. When I try it locally after running for 20 minutes, I get `Test aborted: Giving up after 10000 child processes crashed` with no other info on how to proceed. I know it is rued of me not to have a MCVE, but I don't know how to did in. How should I start debugging this?

**Comment by AltSysrq** [comment]
Whoops, there's [code to generate error messages](https://github.com/AltSysrq/proptest/blob/master/src/test_runner/runner.rs#L676) but nothing to actually print them except for the final test failure.

I'm planning to do a new release tomorrow, so I'll see about adding a "verbose" option or similar.

**Comment by Eh2406** [comment]
Also can we reduce the number of tries to like 100 or 1000? 20 min was a long time to discover it was not doing anything.

**Comment by AltSysrq** [comment]
Hm, to get 10000 processes crashed in 20 minutes, you'd need an average process lifetime of 120ms, so if you didn't set a timeout below that, I'd expect _some_ output from aborting anyway, unless you're getting segfaults or something.

> Also can we reduce the number of tries to like 100 or 1000?

Yeah, this ties into something I was planning for https://github.com/AltSysrq/proptest/issues/91, to allow capping the number of iterations in the shrinking process.

In the mean time, I'd suggest putting `.no_shrink()` on your top-level strategy so you can get at least some information.

**Comment by Eh2406** [comment]
It is possible that in flailing around trying to figure out what was going on I tried a very short time out. If that did not give enough time for the process to startup that would explain the problem. Maybe a warning about two short a timeout should go in the docs?

I was already using `.no_shrink()`, I am glad to here I was on the rite track.

**Comment by AltSysrq** [comment]
> that did not give enough time for the process to startup

Ouch, I hadn't thought of that edge case before. I'll at least add a warning, but it may be possible to catch that happening directly.

**Comment by Eh2406** [comment]
Thanks for all the help! I am trying a longer timeout (3000) and we will see what the runtime is and output looks like. I am hopeful that it won't `Giving up` with a more reasonable number.

**Comment by Eh2406** [comment]
Thanks!

Clear error message. ✔️ Better diagnostic tools. ✔️ Timeout working correctly. ✔️ 

One thing I did notes thow is that the `verbose` is only "real time" if the test is run with ` --nocapture`. Which may be worth mentioning in the docs.
