### ISSUE TITLE
Ability to run until first failure

### ISSUE THREAD

**Issue by vorner** [AltSysrq/proptest#96]
Hello

I was wondering if there's a way to let a test run and keep generating inputs until I either stop it manually or it finds the first failure.

**Comment by AltSysrq** [comment]
Closing for now. If you want to provide more detail that would be useful for a feature addition, feel free to provide it.

**Comment by vorner** [comment]
Thanks, actually I think setting the high number of cases is quite fine for me, I just forgot to mention that.
