### ISSUE TITLE
generating mutable values

### ISSUE THREAD

**Issue by arekfu** [AltSysrq/proptest#99]
Suppose I want to test the following property of `Vec<i32>`: if I push an element into the vector, its length increases by one. I cannot figure out how to take ownership of the generated vector.

Specifically, consider the test function
```rust
proptest! {
    #[test]
    fn test_insert(mut v in any::<Vec<i32>>()) {
        //         ^^^ AY, THERE'S THE RUB
        let len = v.len();
        v.push(42);
        assert_eq!(len + 1, v.len());
    }
}
```
If I try to take `v` as a mutable value, `rustc` complains:
```
src/test.rs|95 col 5 error 507| cannot move out of borrowed content
||     |
|| 95  | /     proptest! {
|| 96  | |         #[test]
|| 97  | |         fn test_insert(mut v in any::<Vec<i32>>()) {
||     | |                        ----- hint: to prevent move, use `ref v` or `ref mut v`
|| 98  | |             let len = v.len();
|| ...   |
|| 101 | |         }
|| 102 | |     }
||     | |_____^ cannot move out of borrowed content
```
And if I use a `ref mut`
```rust
fn test_insert(ref mut v in any::<Vec<i32>>()) {
```
then `rustc` says
```
src/test.rs|97 col 24 error 596| cannot borrow field of immutable binding as mutable
||    |
|| 97 |         fn test_insert(ref mut v in any::<Vec<i32>>()) {
||    |                        ^^^^^^^^^ cannot mutably borrow field of immutable binding
```

The only solution I have found is to take `v` to be a reference and clone it in the test function. I feel a bit silly to do that, because the random vector is generated specifically for the test and I would expect to be able to consume it and mutate it. Am I missing something?

Thank you for your time.

**Comment by Centril** [comment]
Hmm... what version of proptest are you using?
With 0.8.7 I pasted your first snippet into the test-suite and it worked fine;
Indeed, we have tests that should ensure that this works: https://github.com/AltSysrq/proptest/blob/master/src/sugar.rs#L1465

**Comment by arekfu** [comment]
Er, indeed, it works fine in 0.8.7. For some reason I was using 0.7.2. Thank you.
